# snippets/qatrackplus-locations-prod.conf

location /static/ {
    alias /app_data/static/;
    autoindex off;
    access_log off;
    expires 1d;
}

location /media/ {
    alias /app_data/media/;
    autoindex off;
}

include /etc/nginx/snippets/qatrackplus-locations-common.conf;
