CREATE USER qatrack_reports WITH PASSWORD 'qatrackpass';
GRANT CONNECT ON DATABASE qatrackplus TO qatrack_reports;
GRANT USAGE ON SCHEMA public TO qatrack_reports;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO qatrack_reports;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO qatrack_reports;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO qatrack_reports;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO qatrack_reports;
