# Generated by Django 2.1.7 on 2019-04-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import qatrack.qatrack_core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Choose a meaningful title for this report', max_length=255)),
                ('report_type', models.CharField(choices=[('General', [('qc-summary-by-date', 'QC Summary Report')])], max_length=128)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=8)),
                ('include_signature', models.BooleanField(default=True, help_text='Include a signature field at end of PDF reports', verbose_name='Signature')),
                ('filters', qatrack.qatrack_core.fields.JSONField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='report_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='report_modifier', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Select groups who will be able to run this report. Leave blank to keep it private.', to='auth.Group')),
            ],
        ),
    ]
