# Generated by Django 2.1.7 on 2019-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'permissions': (('can_run_reports', 'Can Run Reports'), ('can_create_reports', 'Can create Reports'), ('can_run_sql_reports', 'Can run SQL Data Reports'), ('can_create_sql_reports', 'Can create SQL Data Reports'))},
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Select groups who will be able to view and run this report. Leave blank to keep it private.', to='auth.Group'),
        ),
    ]
