# Generated by Django 2.1.7 on 2019-07-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190704_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='last_sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
