# Generated by Django 2.1.15 on 2020-05-16 01:12

from django.db import migrations


def change_utc_report_type(apps, schema):

    apps.get_model("reports", "SavedReport").objects.filter(
        report_type="utc",
    ).update(
        report_type="test-list-instance-details",
    )


def change_tlid_report_type(apps, schema):

    apps.get_model("reports", "SavedReport").objects.filter(
        report_type="test-list-instance-details",
    ).update(
        report_type="utc",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportschedule_last_sent'),
    ]

    operations = [
        migrations.RunPython(change_utc_report_type, change_tlid_report_type)
    ]
