# Generated by Django 4.2 on 2025-07-22 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0008_auto_20200722_1707"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedreport",
            name="include_logo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="savedreport",
            name="paper_size",
            field=models.CharField(
                choices=[
                    ("letter", 'Letter (8.5" × 11")'),
                    ("a4", "A4 (210mm × 297mm)"),
                ],
                default="letter",
                help_text="Select paper size for PDF reports",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reportnote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="filters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="include_signature",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="report_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("xlsx", "Excel"), ("csv", "CSV")],
                default="pdf",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="report_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="title",
            field=models.CharField(
                help_text="Give your report a descriptive title", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="visible_to",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
    ]
