# Generated by Django 6.0.5 on 2026-05-28 12:50

import qatrack.qatrack_core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_auto_20200722_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportnote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="filters",
            field=qatrack.qatrack_core.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
