# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0009_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportnote",
            options={
                "verbose_name": "Report Note",
                "verbose_name_plural": "Report Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="reportschedule",
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
            },
        ),
        migrations.AlterModelOptions(
            name="savedreport",
            options={
                "ordering": ("title", "created"),
                "permissions": (
                    ("can_run_reports", "Can Run Reports"),
                    ("can_create_reports", "Can create Reports"),
                    ("can_run_sql_reports", "Can run SQL Data Reports"),
                    ("can_create_sql_reports", "Can create SQL Data Reports"),
                ),
                "verbose_name": "Saved Report",
                "verbose_name_plural": "Saved Reports",
            },
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="include_logo",
            field=models.BooleanField(default=True, verbose_name="Include logo"),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="include_signature",
            field=models.BooleanField(default=False, verbose_name="Include signature"),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="paper_size",
            field=models.CharField(
                choices=[
                    ("letter", 'Letter (8.5" × 11")'),
                    ("a4", "A4 (210mm × 297mm)"),
                ],
                default="letter",
                help_text="Select paper size for PDF reports",
                max_length=10,
                verbose_name="Paper size",
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="report_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("xlsx", "Excel"), ("csv", "CSV")],
                default="pdf",
                max_length=4,
                verbose_name="Report format",
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="report_type",
            field=models.CharField(max_length=255, verbose_name="Report type"),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="title",
            field=models.CharField(
                help_text="Give your report a descriptive title",
                max_length=255,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, to="auth.group", verbose_name="Visible to"
            ),
        ),
    ]
