# Generated by Django 4.2 on 2025-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("organization", "name"),
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("name",),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={
                "ordering": ("document", "tag_name"),
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.AddField(
            model_name="requirement",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier for the requirement",
                max_length=255,
                verbose_name="DOI",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="PDF document related to this requirement",
                null=True,
                upload_to="accreditation/requirements/",
                verbose_name="PDF File",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year when the requirement was published or established",
                null=True,
                verbose_name="Year",
            ),
        ),
    ]
