# Generated by Django 4.2 on 2025-08-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accreditation",
            "0002_alter_document_options_alter_organization_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirement",
            name="doi",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="year",
        ),
        migrations.AddField(
            model_name="document",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier for the document",
                max_length=255,
                verbose_name="DOI",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="PDF document file",
                null=True,
                upload_to="accreditation/documents/",
                verbose_name="PDF File",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year when the document was published or established",
                null=True,
                verbose_name="Year",
            ),
        ),
    ]
