# Generated by Django 4.2 on 2025-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accreditation",
            "0003_remove_requirement_doi_remove_requirement_pdf_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="energy",
            field=models.CharField(
                choices=[("photon", "Photon"), ("electron", "Electron")],
                default="photon",
                help_text="Energy type for this requirement",
                max_length=20,
                verbose_name="Energy",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="international_recommendation",
            field=models.CharField(
                choices=[
                    ("internationally_required", "Internationally Required"),
                    ("internationally_optional", "Internationally Optional"),
                ],
                default="internationally_optional",
                help_text="International requirement status",
                max_length=30,
                verbose_name="International Recommendation",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("bi_annually", "Bi-Annually"),
                    ("annually", "Annually"),
                ],
                default="monthly",
                help_text="How often this requirement should be performed",
                max_length=20,
                verbose_name="Periodicity",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_class",
            field=models.CharField(
                choices=[
                    ("mechanical_imaging", "Mechanical Imaging"),
                    ("dosimetry_relative", "Dosimetry - Relative"),
                    ("dosimetry_absolute", "Dosimetry - Absolute"),
                ],
                default="mechanical_imaging",
                help_text="Classification of this requirement",
                max_length=30,
                verbose_name="Requirement Class",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("recommended", "Recommended"),
                    ("optional", "Optional"),
                ],
                default="mandatory",
                help_text="Whether this requirement is mandatory, recommended, or optional",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="tolerance",
            field=models.CharField(
                blank=True,
                help_text="Tolerance specification for this requirement",
                max_length=255,
                verbose_name="Tolerance",
            ),
        ),
    ]
