# Generated by Django 4.2 on 2025-08-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accreditation", "0004_requirement_energy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirement",
            name="requirement_type",
        ),
        migrations.AddField(
            model_name="requirement",
            name="compliance_level",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("recommended", "Recommended"),
                    ("optional", "Optional"),
                ],
                default="mandatory",
                help_text="Whether this requirement is mandatory, recommended, or optional",
                max_length=20,
                verbose_name="Compliance Level",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(
                help_text="Name of the document",
                max_length=255,
                verbose_name="Document Name",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Document file",
                null=True,
                upload_to="accreditation/documents/",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="tag_name",
            field=models.CharField(
                help_text="identifier/tag for the document",
                max_length=100,
                verbose_name="Tag Name",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year when the document was published",
                null=True,
                verbose_name="Year",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("bi_annually", "Bi-Annually"),
                    ("annually", "Annually"),
                ],
                default="monthly",
                help_text="Frequency of requirement performance",
                max_length=20,
                verbose_name="Periodicity",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="tag_name",
            field=models.CharField(
                help_text="identifier/tag for the requirement",
                max_length=100,
                verbose_name="Requirement Tag Name",
            ),
        ),
    ]
