from django.urls import re_path
from qatrack.service_log import views

urlpatterns = [
    re_path(r"^$", views.SLDashboard.as_view(), name="sl_dash"),
    re_path(r'^event/$', views.ServiceEventsBaseList.as_view(), name="sl_list_all"),
    re_path(r'^event/create/$', views.CreateServiceEvent.as_view(), name='sl_new'),
    re_path(r'^event/create/choose-unit/$', views.ChooseUnitForNewSE.as_view(), name="sl_unit_new"),
    re_path(r'^event/edit(?:/(?P<pk>\d+))?/$', views.UpdateServiceEvent.as_view(), name="sl_edit"),
    re_path(r'^event/details(?:/(?P<pk>\d+))?/$', views.DetailsServiceEvent.as_view(), name="sl_details"),
    re_path(r'^event/delete(?:/(?P<pk>\d+))?/$', views.DeleteServiceEvent.as_view(), name='se_delete'),
    re_path(r'^event/review-required/$', views.ServiceEventsReviewRequiredList.as_view(), name="sl_list_review_required"),
    re_path(r'^event/review/choose-unit/$', views.ChooseUnitForViewSE.as_view(), name="sl_unit_view_se"),
    re_path(r'^event/unit/(?P<unit_number>\d+)/$', views.ServiceEventsByUnitList.as_view(), name="sl_list_by_unit"),
    re_path(r'^event/initiated-by/(?P<tli_pk>\d+)/$', views.ServiceEventsInitiatedByList.as_view(), name="sl_list_initiated_by"),
    re_path(r'^event/return-to-service-for/(?P<tli_pk>\d+)/$', views.ServiceEventsReturnToServiceForList.as_view(), name="sl_list_return_to_service_for"),
    re_path(r'^event/status/(?P<pk>\d+)/$', views.ServiceEventsByStatusList.as_view(), name="sl_list_by_status"),
    re_path(r'^event/report/(?P<pk>\d+)/$', views.service_log_report, name="sl_service_event_report"),
    re_path(r'^rtsqa/$', views.ReturnToServiceQABaseList.as_view(), name="rtsqa_list_all"),
    re_path(r'^rtsqa/incomplete/$', views.ReturnToServiceQAIncompleteList.as_view(), name="rtsqa_list_incomplete"),
    re_path(r'^rtsqa/unreviewed/$', views.ReturnToServiceQAUnreviewedList.as_view(), name="rtsqa_list_unreviewed"),
    re_path(r'^rtsqa/event/(?P<se_pk>\d+)$', views.ReturnToServiceQAForEventList.as_view(), name="rtsqa_list_for_event"),
    re_path(r'^se-searcher/$', views.se_searcher, name="se_searcher"),
    re_path(r'^tli-select(?:/(?P<pk>\d+))?(?:/(?P<form>[a-zA-Z0-9-_]+)/)?$', views.TLISelect.as_view(), name="tli_select"),
    re_path(r'^tli-statuses/$', views.tli_statuses, name="tli_statuses"),
    re_path(r'^unit-sa_utc/$', views.unit_sa_utc, name="unit_sa_utc"),
    re_path(r'^err/$', views.ErrorView.as_view(), name='err'),
    re_path(r'^down-time/$', views.ServiceEventDownTimesList.as_view(), name='se_down_time'),
    re_path(r'^handle-unit-down-time/$', views.handle_unit_down_time, name='handle_unit_down_time'),
    re_path(r'^templates/create_ajax/$', views.CreateServiceEventTemplateAjax.as_view(), name='create_se_template'),
    re_path(r'^templates/searcher/$', views.service_event_template_searcher, name='se_template_searcher'),
    re_path(r'^event/schedule/all/$', views.ServiceEventScheduleList.as_view(), name='se_schedule_list_all'),
    re_path(r'^event/schedule/due-and-overdue/$', views.DueAndOverdue.as_view(), name='se_schedule_due'),
    re_path(r'^event/schedule/due-dates/$', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates'),
    re_path(r'^event/schedule/due-dates-user/$', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates_user'),
]
