# Load variables set in .env file
set dotenv-path := ".env"

# Set shells used for executing recipes on Linux and Windows
set shell := ["bash", "-uc"]
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

export BUILDKIT_PROGRESS := "plain"

# Use of compose.dev.yaml file to override compose.yaml is decided by setting the QATDEV env variable to 1.
# Any other value, or the variable being unset ends up using production settings.
export COMPOSE_FILE := if env("QATDEV", "0") == "1" {
    "compose.yaml:compose.dev.yaml"
} else {
    "compose.yaml"
}
export DOCKER_TAG := if env("QATDEV", "0") == "1" {
    ":dev"
} else {
    ":prod"
}

# Run docker.
docker *args:
    @docker {{args}}

# Run docker compose.
[linux]
compose *args:
    @if [ "${QATDEV:-0}" = "1" ]; then HOST_GID="${HOST_GID:-$(id -g)}" HOST_UID="${HOST_UID:-$(id -u)}" docker compose {{args}}; else docker compose {{args}}; fi

[windows]
compose *args:
    @docker compose {{args}} 

# Run django management commands in the running container.
manage *args:
    @docker compose exec django python manage.py {{args}}
