# Generated by Django 2.2.17 on 2021-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_auto_20210202_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulttype',
            name='code',
            field=models.CharField(db_index=True, help_text='Enter the fault code or number', max_length=255, verbose_name='code'),
        ),
    ]
