# Generated by Django 2.1.15 on 2021-01-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0025_auto_20210114_0951'),
        ('faults', '0003_auto_20210121_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='related_service_events',
            field=models.ManyToManyField(blank=True, help_text='Enter the service event IDs of any related service events.', to='service_log.ServiceEvent', verbose_name='related service events'),
        ),
    ]
