# Generated by Django 2.2.18 on 2021-03-17 19:25

from django.db import migrations


def nullify_treatment_techniques(apps, schema):

    Fault = apps.get_model("faults", "Fault")
    Fault.objects.update(treatment_technique=None)


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0003_auto_20210202_1703'),
    ]

    operations = [
        migrations.RunPython(nullify_treatment_techniques, lambda a, sc: None),
    ]
