# Generated by Django 2.2.18 on 2021-03-18 03:03

from django.db import migrations


def move_to_fault_types(apps, schema):

    Fault = apps.get_model("faults", "Fault")
    for fault in Fault.objects.all():
        fault.fault_types.add(fault.fault_type)


def move_to_fault_type(apps, schema):

    Fault = apps.get_model("faults", "Fault")
    for fault in Fault.objects.all():
        fault.fault_type = fault.fault_types.all()[:1]
        fault.save()
        fault.fault_types.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0007_fault_fault_types'),
    ]

    operations = [
        migrations.RunPython(move_to_fault_types, move_to_fault_type),
    ]
