# Generated by Django 2.2.18 on 2021-03-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0008_move_fault_type_to_fault_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='fault_type',
        ),
    ]
