# Generated by Django 2.2.18 on 2021-03-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0009_remove_fault_fault_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='modality',
            field=models.ForeignKey(blank=True, help_text='Select the treatment or imaging modality being used when this fault occurred (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faults', to='units.Modality', verbose_name='treatment or imaging modality'),
        ),
    ]
