# Generated by Django 2.2.18 on 2022-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0012_eliminate_duplicate_fault_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulttype',
            name='code',
            field=models.CharField(db_index=True, help_text='Enter the fault code or number', max_length=255, unique=True, verbose_name='code'),
        ),
    ]
