# Generated by Django 4.2 on 2025-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0013_auto_20220617_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faultreviewgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faultreviewinstance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faulttype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
