# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0014_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fault",
            options={
                "ordering": ("-occurred",),
                "permissions": (("can_review", "Can review faults"),),
                "verbose_name": "Fault",
                "verbose_name_plural": "Faults",
            },
        ),
        migrations.AlterModelOptions(
            name="faultreviewgroup",
            options={
                "verbose_name": "Fault Review Group",
                "verbose_name_plural": "Fault Review Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="faulttype",
            options={
                "ordering": ("code",),
                "verbose_name": "Fault Type",
                "verbose_name_plural": "Fault Types",
            },
        ),
    ]
