"""Record the outstanding field state for faults. No schema change.

Part of one bundled set across seven apps, 195 operations in total, of which 7 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every operation is metadata.** `sqlmigrate` renders all 195 of them as `-- (no-op)`
on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine. Applying this
writes a row to `django_migrations` and touches nothing else.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faults", "0015_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faults_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="fault",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faults_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="fault",
            name="occurred",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When did this fault occur.",
                verbose_name="Date & Time fault occurred",
            ),
        ),
        migrations.AlterField(
            model_name="faultreviewinstance",
            name="reviewed_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faults_reviewed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AlterField(
            model_name="faulttype",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="Unique URL friendly identifier made of lowercase characters, dashes, and underscores.",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
