server {
    listen 80;
    server_name _;
    charset utf-8;

    # Maximum upload size
    client_max_body_size 100M;

    location /static/ {
        alias /home/YOURUSERNAMEHERE/web/qatrackplus/qatrack/static/;
    }

    location /media/ {
        alias /home/YOURUSERNAMEHERE/web/qatrackplus/qatrack/media/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_connect_timeout 5s;
        proxy_read_timeout 130s;
        proxy_send_timeout 130s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}