# Generated by Django 2.1.5 on 2019-02-06 16:06

from django.contrib.auth.hashers import make_password
from django.db import migrations


def update_internal_pass(apps, schema):
    User = apps.get_model("auth", "User")
    user = User.objects.get(username="QATrack+ Internal")
    user.password = make_password(User.objects.make_random_password())
    user.save()


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunPython(update_internal_pass, lambda a, s: None)
    ]
