# Generated by Django 2.1.5 on 2019-02-06 16:06

from django.contrib.auth.hashers import make_password
from django.db import migrations


def update_internal_pass(apps, schema):
    User = apps.get_model("auth", "User")
    user = User.objects.get(username="QATrack+ Internal")
    from django.utils.crypto import get_random_string
    user.password = make_password(get_random_string(length=12))
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0030_auto_20190129_2156'),
    ]

    operations = [
        migrations.RunPython(update_internal_pass, lambda a, s: None)
    ]
