# Generated by Django 2.2.18 on 2021-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activedirectorygroupmap_defaultgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedirectorygroupmap',
            name='ad_group',
            field=models.CharField(help_text='Enter the name of the group from your Active Directory Server.', max_length=255, unique=True, verbose_name='Active Directory Group'),
        ),
    ]
