# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultgroup",
            options={
                "verbose_name": "Default Group",
                "verbose_name_plural": "Default Groups",
            },
        ),
    ]
