[program:gunicorn]
command=/home/YOURUSERNAMEHERE/web/qatrackplus/.venv/bin/gunicorn qatrack.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 120
directory=/home/YOURUSERNAMEHERE/web/qatrackplus
user=YOURUSERNAMEHERE
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/YOURUSERNAMEHERE/web/qatrackplus/logs/gunicorn.log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8
