import django.forms as forms
from django.utils.translation import ugettext as _

from django.contrib import admin
from models import TaskList, TaskListItem

import re

class TaskListAdmin(admin.ModelAdmin):
    prepopulated_fields =  {'slug': ('name',)}

#============================================================================
class TaskListItemAdminForm(forms.ModelForm):
    """custom tasklistitem form to ensure valid shortname to be used in Python snippets"""
    VARIALBLE_RE = re.compile("^[a-zA-Z_]+[0-9a-zA-Z_]*")
    #----------------------------------------------------------------------
    def clean_short_name(self):
        """replace any dashes in short_name (short_name is an autogenerated slug field) with underscores"""
        short_name = self.cleaned_data["short_name"]
        if self.VARIALBLE_RE.match(short_name):
            raise forms.ValidationError(
                _("Short names must contain only letters, numbers and underscores and start with a ltter or underscore")
            )
        return short_name


class TaskListItemAdmin(admin.ModelAdmin):
    readonly_fields = ("order", )
    form = TaskListItemAdminForm


admin.site.register([TaskList],TaskListAdmin)
admin.site.register([TaskListItem],TaskListItemAdmin)