import datetime

import django.forms as forms
import django.db

from django.utils.translation import ugettext as _
from django.contrib import admin

import qatrack.qa.models as models
from qatrack.units.models import Unit
import qatrack.settings as settings
import re

#============================================================================
class SaveUserMixin(object):
    """A Mixin to save creating user and modifiying user

    Set editable=False on the created_by and modified_by model you
    want to use this for.
    """

    #----------------------------------------------------------------------
    def save_model(self, request, obj, form, change):
        """set user and modified date time"""
        if not obj.pk:
            obj.created_by = request.user
            obj.created = datetime.datetime.now()
        obj.modified_by = request.user
        super(SaveUserMixin, self).save_model(request, obj, form, change)
        #obj.save()

#============================================================================
class BasicSaveUserAdmin(SaveUserMixin, admin.ModelAdmin):
    """manage reference values for task list items"""

#----------------------------------------------------------------------
def title_case_name(obj):
    return ("%s"%obj.name).title()
title_case_name.short_description = "Name"

#============================================================================
class CategoryAdmin(admin.ModelAdmin):
    """QA categories admin"""
    prepopulated_fields =  {'slug': ('name',)}

#============================================================================
class TaskListItemInfoForm(forms.ModelForm):
    reference_value = forms.FloatField(
        label=_("Update reference"),
        help_text=_("For Yes/No tests, enter 1 for Yes and 0 for No"),
    )
    reference_type = forms.ChoiceField(choices=models.Reference.TYPE_CHOICES)

    class Meta:
        model = models.TaskListItemUnitInfo

    #----------------------------------------------------------------------
    def clean(self):
        """make sure valid numbers are entered for boolean data"""

        if "reference_value" not in self.cleaned_data:
            return self.cleaned_data

        ref_value = self.cleaned_data["reference_value"]
        ref_type = self.cleaned_data["reference_type"]

        if ref_type == models.Reference.BOOLEAN:
            if int(ref_value) not in (0,1):
                raise forms.ValidationError(_("Yes/No values must be 0 or 1"))

        return self.cleaned_data




class TaskListItemInfoAdmin(admin.ModelAdmin):
    """"""
    form = TaskListItemInfoForm
    fields = (
        "unit", "task_list_item",
        "reference", "tolerance",
        "reference_value", "reference_type",
    )
    list_display = ["task_list_item", "unit", "reference", "tolerance"]
    list_filter = ["unit","task_list_item__category"]
    readonly_fields = ("task_list_item","unit","reference")

    #----------------------------------------------------------------------
    def save_model(self, request, item_info, form, change):
        """create new reference when user updates value"""
        ref = models.Reference(
            value=form["reference_value"].value(),
            ref_type = form["reference_type"].value(),
            created_by = request.user,
            modified_by = request.user,
            name = "%s %s" % (item_info.unit.name,item_info.task_list_item.name)
        )
        ref.save()
        item_info.reference = ref
        super(TaskListItemInfoAdmin,self).save_model(request,item_info,form,change)


#============================================================================
class TaskListAdmin(SaveUserMixin, admin.ModelAdmin):
    prepopulated_fields =  {'slug': ('name',)}
    list_display = (title_case_name, "modified", "modified_by", "active")
    filter_horizontal= ("task_list_items", "sublists", )

#============================================================================
class TaskListItemAdminForm(forms.ModelForm):
    """custom tasklistitem form to ensure valid shortname to be used in Python snippets"""
    VARIABLE_RE = re.compile("^[a-zA-Z_]+[0-9a-zA-Z_]*")
    #----------------------------------------------------------------------
    def clean_short_name(self):
        """replace any dashes in short_name (short_name is an autogenerated slug field) with underscores"""
        short_name = self.cleaned_data["short_name"]
        if not self.VARIABLE_RE.match(short_name):
            raise forms.ValidationError(
                _("Short names must contain only letters, numbers and underscores and start with a ltter or underscore")
            )
        return short_name

#============================================================================
class CompositeItemAdminForm(TaskListItemAdminForm):
    RESULT_RE = re.compile("^result\s*=\s*[_0-9.a-zA-Z]+.*$",re.MULTILINE)
    #hidden_fields = ("constant_value", "task_type")
    class Meta:
        exclude = ("constant_value", "task_type")
    #----------------------------------------------------------------------
    def clean_snippet(self):
        """ensure there's a result defined in the snippet"""
        snippet = self.cleaned_data["snippet"]
        if not self.RESULT_RE.findall(snippet):
            raise forms.ValidationError(
                _('Snippet must contain a result line (e.g. result = my_var/another_var*2)')
            )

        return snippet

#============================================================================
class TaskListItemAdmin(SaveUserMixin, admin.ModelAdmin):
    form = TaskListItemAdminForm
    list_display = ["name","category", "task_type", "modified", "modified_by","set_references"]

#============================================================================
class CompositeTaskListItemAdmin(TaskListItemAdmin):
    form = CompositeItemAdminForm
    filter_horizontal = ("dependencies",)

#============================================================================
class UnitTaskListAdmin(admin.ModelAdmin):
    readonly_fields = ("unit","frequency",)
    filter_horizontal = ("task_lists",)
    list_display = ["name", "unit", "frequency"]
    list_filter = ["unit", "frequency"]


#============================================================================
class TaskListCycleMembershipInline(admin.TabularInline):

    model = models.TaskListCycleMembership
    extra = 1

#============================================================================
class TaskListCycleAdmin(admin.ModelAdmin):
    """Admin for daily task list cycles"""
    inlines = [TaskListCycleMembershipInline]

    class Media:
        js = ("m2m_drag_admin.js",)

admin.site.register([models.Tolerance], BasicSaveUserAdmin)
admin.site.register([models.Category], CategoryAdmin)
admin.site.register([models.TaskList],TaskListAdmin)
admin.site.register([models.TaskListItem],TaskListItemAdmin)
admin.site.register([ models.CompositeTaskListItem],CompositeTaskListItemAdmin)
admin.site.register([models.TaskListItemUnitInfo],TaskListItemInfoAdmin)
admin.site.register([models.UnitTaskLists],UnitTaskListAdmin)

admin.site.register([models.TaskListCycle],TaskListCycleAdmin)