# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 23:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qatrack.attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0002_auto_20161218_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=qatrack.attachments.models.get_upload_path, verbose_name='Attachment')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Test')),
                ('testinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestInstance')),
                ('testlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestList')),
                ('testlistcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestListCycle')),
                ('testlistinstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestListInstance')),
            ],
        ),
    ]
