# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qatrack.attachments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('qa', '0003_auto_20161128_2055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=qatrack.attachments.models.get_upload_path, verbose_name='Attachment')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Test')),
                ('testinstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestInstance')),
                ('testlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestList')),
                ('testlistcycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestListCycle')),
                ('testlistinstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestListInstance')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit')),
                ('unittestcollection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.UnitTestCollection')),
            ],
        ),
    ]
