# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import qatrack.attachments.models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_attachment_serviceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(max_length=255, upload_to=qatrack.attachments.models.get_upload_path, verbose_name='Attachment'),
        ),
    ]
