# Generated by Django 2.1.5 on 2019-01-30 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_add_attach_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
