"""Record the outstanding field state for attachments. No schema change.

Part of one bundled set across seven apps, 195 operations in total, of which 10 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every operation is metadata.** `sqlmigrate` renders all 195 of them as `-- (no-op)`
on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine. Applying this
writes a row to `django_migrations` and touches nothing else.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0019_v4_0_2_final"),
        ("service_log", "0028_v4_0_final"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0060_v4_0_final"),
        ("faults", "0016_v4_0_2_final"),
        ("attachments", "0010_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="fault",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="faults.fault",
                verbose_name="Fault",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="parts.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="serviceevent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_log.serviceevent",
                verbose_name="Service Event",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.test",
                verbose_name="Test",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="testinstance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testinstance",
                verbose_name="Test Instance",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="testlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlist",
                verbose_name="Test List",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="testlistcycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlistcycle",
                verbose_name="Test List Cycle",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="testlistinstance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlistinstance",
                verbose_name="Test List Instance",
            ),
        ),
    ]
