# Generated by Django 2.2.28 on 2022-10-24 19:07

import pytz
from django.conf import settings
from django.db import migrations
from django.utils import timezone


def update_recurrences(apps, schema):
    """Ensure all recurrence rules are localized correctly"""

    tz = pytz.timezone(settings.TIME_ZONE)
    models = [
        ("qa.Frequency", 'recurrences'),
        ("notifications.FaultsReviewNotice", 'recurrences'),
        ("notifications.QCReviewNotice", 'recurrences'),
        ("notifications.QCSchedulingNotice", 'recurrences'),
        ("notifications.ServiceEventReviewNotice", 'recurrences'),
        ("notifications.ServiceEventSchedulingNotice", 'recurrences'),
        ("reports.ReportSchedule", 'schedule'),
    ]

    recurrence_start = tz.localize(timezone.datetime(2012, 1, 1))

    for app_model, field in models:
        app, model = app_model.split('.')
        model = apps.get_model(app, model)
        for obj in model.objects.all():
            getattr(obj, field).dtstart = recurrence_start
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200722_1707'),
        ('notifications', '0024_serviceeventschedulingnotice'),
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.RunPython(update_recurrences, lambda apps, schema: None),
    ]

