# Generated by Django 3.2.23 on 2024-12-18 21:29

from zoneinfo import ZoneInfo
from django.db import migrations
from django.utils import timezone
from django.conf import settings


def update_recurrences(apps, schema_editor):
    """Update start date for any existing recurrence fields"""
    # Get models dynamically
    tz = ZoneInfo(settings.TIME_ZONE)

    models = [
        ("faults", "Fault"),
        ("parts", "PartStorageCollection"),
        ("qa", "FrequencyRule"),
        ("service_log", "SloGroup"),
    ]

    for app_label, model_name in models:
        try:
            model = apps.get_model(app_label, model_name)
            recurrence_start = timezone.datetime(2012, 1, 1).replace(tzinfo=tz)
            for obj in model.objects.all():
                if hasattr(obj, 'recurrences'):
                    if obj.recurrences:
                        obj.recurrences.dtstart = recurrence_start
                    obj.save()
        except LookupError:
            pass  # Model doesn't exist yet


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200722_1707'),
        ('notifications', '0024_serviceeventschedulingnotice'),
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.RunPython(update_recurrences, lambda apps, schema: None),
    ]

