# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_level', models.IntegerField(choices=[(10, 'Notify on Tolerance or Action'), (20, 'Notify on Test at Action level only')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', unique=True)),
            ],
        ),
    ]
