# Generated by Django 2.1.7 on 2019-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_copy_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='warning_level',
        ),
    ]
