# Generated by Django 2.1.7 on 2019-08-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0035_remove_sql_reports_perms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('units', '0011_auto_20190410_1101'),
        ('notifications', '0009_remove_notificationsubscription_warning_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCCompletedNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(0, 'Notify when Test List completed'), (10, 'Notify on Tolerance or Action'), (20, 'Notify on Test at Action level only'), (30, 'Follow up notification')], verbose_name='Notification Type')),
                ('follow_up_days', models.PositiveIntegerField(blank=True, help_text='Number of days after TestList completion to send follow up email. Used for follow up notifications only', null=True, verbose_name='Follow up days')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this group of recipients', max_length=255)),
                ('emails', models.TextField(blank=True, help_text='Enter a comma separated list of extra emails this report should be sent to', verbose_name='Extra recipient emails')),
                ('groups', models.ManyToManyField(blank=True, help_text='Select which groups this notification should be sent to.', to='auth.Group')),
                ('users', models.ManyToManyField(blank=True, help_text='Select individual users to include in these notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestListGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this group of TestLists', max_length=255)),
                ('test_lists', models.ManyToManyField(help_text='Select which Test Lists should be included in this notification group.', to='qa.TestList')),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this group of TestLists', max_length=255)),
                ('units', models.ManyToManyField(help_text='Select which Units should be included in this notification group.', to='units.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='qccompletednotice',
            name='recipients',
            field=models.ForeignKey(help_text='Choose the group of recipients who should receive these notifications', on_delete=django.db.models.deletion.PROTECT, to='notifications.RecipientGroup', verbose_name='Recipients'),
        ),
        migrations.AddField(
            model_name='qccompletednotice',
            name='test_lists',
            field=models.ForeignKey(blank=True, help_text='Select which group of Test Lists this notification should be limited to. Leave blank to include all Test Lists.', null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.TestListGroup'),
        ),
        migrations.AddField(
            model_name='qccompletednotice',
            name='units',
            field=models.ForeignKey(blank=True, help_text='Select which group of Units this notification should be limited to. Leave blank to include all units', null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.UnitGroup', verbose_name='Unit group filter'),
        ),
    ]
