# Generated by Django 2.1.7 on 2019-08-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_copy_qccompleted_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='test_lists',
        ),
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='units',
        ),
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='qccompletednotice',
            options={'verbose_name': 'QC Completed Notice'},
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='name',
            field=models.CharField(help_text='Enter a name for this group of Units', max_length=255),
        ),
        migrations.DeleteModel(
            name='NotificationSubscription',
        ),
    ]
