# Generated by Django 2.1.11 on 2019-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20190803_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcschedulingnotice',
            name='last_sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
