# Generated by Django 2.1.15 on 2020-05-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_qcreviewnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreviewnotice',
            name='send_empty',
            field=models.BooleanField(default=False, help_text="Check to send notices even if there's no unreviewed QC to currently notify about", verbose_name='Send Empty Notices'),
        ),
        migrations.AddField(
            model_name='qcschedulingnotice',
            name='send_empty',
            field=models.BooleanField(default=False, help_text="Check to send notices even if there's no QC to currently notify about", verbose_name='Send Empty Notices'),
        ),
        migrations.AlterField(
            model_name='qccompletednotice',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Notify when Test List completed'), (10, 'Notify on Test at Tolerance or Action level'), (20, 'Notify on Test at Action level only'), (30, 'Follow up notification')], verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='qcschedulingnotice',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Notify About All Test Lists Due Dates'), (10, 'Notify About Test Lists Currently Due & Overdue'), (20, 'Notify About Test Lists Currently Due & Overdue, and Upcoming Due Dates'), (30, 'Notify About Test Lists Upcoming Due Dates Only')], verbose_name='Notification Type'),
        ),
    ]
