# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0025_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faultnotice",
            options={
                "verbose_name": "Fault Logged Notice",
                "verbose_name_plural": "Fault Logged Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="faultsreviewnotice",
            options={
                "verbose_name": "Fault Review Notice",
                "verbose_name_plural": "Fault Review Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="partcategorygroup",
            options={
                "verbose_name": "Part Category Group",
                "verbose_name_plural": "Part Category Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="partnotice",
            options={
                "verbose_name": "Part Notice",
                "verbose_name_plural": "Part Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="qccompletednotice",
            options={
                "verbose_name": "QC Completed Notice",
                "verbose_name_plural": "QC Completed Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="qcreviewnotice",
            options={
                "verbose_name": "QC Review Notice",
                "verbose_name_plural": "QC Review Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="qcschedulingnotice",
            options={
                "verbose_name": "QC Scheduling Notice",
                "verbose_name_plural": "QC Scheduling Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="recipientgroup",
            options={
                "verbose_name": "Recipient Group",
                "verbose_name_plural": "Recipient Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventnotice",
            options={
                "verbose_name": "Service Event Notice",
                "verbose_name_plural": "Service Event Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventreviewnotice",
            options={
                "verbose_name": "Service Event Review Notice",
                "verbose_name_plural": "Service Event Review Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventschedulingnotice",
            options={
                "verbose_name": "Service Event Scheduling Notice",
                "verbose_name_plural": "Service Event Scheduling Notices",
            },
        ),
        migrations.AlterModelOptions(
            name="testlistgroup",
            options={
                "verbose_name": "Test List Group",
                "verbose_name_plural": "Test List Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="unitgroup",
            options={
                "verbose_name": "Unit Group",
                "verbose_name_plural": "Unit Groups",
            },
        ),
    ]
