# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20180426_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='unitavailabletimeedit',
            options={'default_permissions': (), 'get_latest_by': 'date', 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='unitclass',
            options={'ordering': ('name',), 'verbose_name_plural': 'Unit classes'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ('vendor__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='unittype',
            unique_together=set([('name', 'model', 'vendor', 'unit_class')]),
        ),
    ]
