# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_auto_20180601_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='date_acceptance',
            field=models.DateField(help_text='Changing acceptance date will delete unit available times that occur before it', verbose_name='Acceptance date'),
        ),
    ]
