# Generated by Django 1.11.12 on 2018-07-25 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('units', '0008_auto_20180725_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='restricted',
        ),
    ]
