# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def make_all_serviceable(apps, schema):

    Unit = apps.get_model("units", "Unit")
    active = Unit.objects.filter(active=True)
    all_not_serviceable = not any(active.values_list("is_serviceable", flat=True))

    if all_not_serviceable:
        # user hasn't changed anything themselves so we can update without
        # affecting their modifications
        Unit.objects.filter(active=True).update(is_serviceable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_remove_unit_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='is_serviceable',
            field=models.BooleanField(default=True, help_text='Set to true to enable this unit to be selectable in service events'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.UnitType', verbose_name='Unit Type'),
        ),
        migrations.RunPython(make_all_serviceable, lambda a, s: None)
    ]
