# Generated by Django 2.1.11 on 2019-11-29 04:39

from django.db import migrations
from django.utils.text import slugify


def add_site_slugs(apps, schema):
    Site = apps.get_model("units", "Site")
    for s in Site.objects.all():
        base_slug = slugify(s.name)
        slug = base_slug
        ival = 0
        while Site.objects.filter(slug=slug).count() > 0:
            ival += 1
            slug = "%s-%d" % (base_slug, ival)

        s.slug = slugify(slug)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_site_slug'),
    ]

    operations = [migrations.RunPython(add_site_slugs, lambda apps, sch: None)]
