# Generated by Django 2.1.15 on 2021-01-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_datetimes_to_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        help_text='Name of this treatment technique', max_length=255, unique=True, verbose_name='name'
                    )
                ),
            ],
            options={
                'verbose_name': 'treatment technique',
                'verbose_name_plural': 'treatment techniques',
                'ordering': ('name',),
            },
        ),
    ]
