# Generated by Django 2.2.18 on 2021-03-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0005_auto_20210317_1538'),
        ('units', '0017_auto_20210126_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='treatment_techniques',
        ),
        migrations.DeleteModel(
            name='TreatmentTechnique',
        ),
    ]
