# Generated by Django 2.1.15 on 2021-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_treatmenttechnique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='treatment_techniques',
            field=models.ManyToManyField(to='units.TreatmentTechnique'),
        ),
    ]
