# Generated by Django 2.2.18 on 2021-05-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_auto_20210323_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['number'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='scale',
            field=models.CharField(blank=True, choices=[('ELEKTA', 'Elekta'), ('ELEKTA_IEC', 'Elekta IEC'), ('ELEKTA_IEC601', 'Elekta IEC601'), ('IEC61217', 'IEC61217'), ('SATURNE', 'Saturne'), ('SATURNE_MS', 'Saturne MS'), ('SIEMENS', 'Siemens'), ('SIEMENS_IEC', 'Siemens IEC'), ('VARIAN_IEC', 'Varian IEC'), ('VARIAN_STANDARD', 'Varian Standard')], default='', help_text='Coordinate scale of the machine', max_length=256),
        ),
    ]
