# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0020_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modality",
            options={
                "verbose_name": "Treatment and Imaging Modality",
                "verbose_name_plural": "Treatment and Imaging Modalities",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ("name",),
                "verbose_name": "Clinical Site",
                "verbose_name_plural": "Clinical Sites",
            },
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={
                "ordering": ["number"],
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.AlterModelOptions(
            name="unitavailabletime",
            options={
                "default_permissions": ("change",),
                "get_latest_by": "date_changed",
                "ordering": ["-date_changed"],
                "verbose_name": "Unit Available Time",
                "verbose_name_plural": "Unit Available Times",
            },
        ),
        migrations.AlterModelOptions(
            name="unitavailabletimeedit",
            options={
                "default_permissions": (),
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "Unit Available Time Edit",
                "verbose_name_plural": "Unit Available Time Edits",
            },
        ),
        migrations.AlterModelOptions(
            name="unitclass",
            options={
                "ordering": ("name",),
                "verbose_name": "Unit Class",
                "verbose_name_plural": "Unit Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="unittype",
            options={
                "ordering": ("vendor__name", "name"),
                "verbose_name": "Unit Type",
                "verbose_name_plural": "Unit Types",
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ("name",),
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
            },
        ),
        migrations.AlterField(
            model_name="unit",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="units.site",
                verbose_name="Clinical Site",
            ),
        ),
    ]
