"""Record the outstanding field state for units, and repair 1 unique index
SQL Server dropped.

Part of one bundled set across seven apps, 195 operations in total, of which 20 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every `AlterField` here is metadata.** `sqlmigrate` renders all 195 of them as
`-- (no-op)` on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine.

**The `RunPython` at the end is the one part that can change a schema.** It adds back
unique constraints the database has stopped enforcing: `mssql-django` drops a unique
index when an unrelated `AlterField` retypes a model's primary key and never recreates
it, which the 4.0 migrations did to every model, so a SQL Server installation silently
stopped enforcing uniqueness these models declare. 1 of this app's constraint is affected, 1 of
it needing a filtered index because SQL Server treats NULLs as equal where Django does
not.

**It names no engine.** Each constraint is repaired only if the database is not
currently enforcing it, so on SQLite, PostgreSQL and MySQL - measured, all three report
nothing to repair - every one is skipped and no DDL is issued. Django generates the SQL
through `schema_editor.add_constraint`, so each backend emits its own syntax rather than
this migration guessing it.

It changes no migration state (the models already declare this uniqueness - the database
is what diverged), and where duplicate rows already exist it reports them and moves on
rather than failing the upgrade. Run `manage.py check_unique_constraints` first to see
whether anything will be skipped.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.db import migrations, models

from qatrack.qatrack_core.unique_repair import (
    remove_repaired_constraints,
    repair_unique_constraints,
)
import django.db.models.deletion



# Unique constraints the database has stopped enforcing - see
# qatrack/qatrack_core/unique_repair.py for the mechanism and why this is a repair
# rather than a state change. In practice this is SQL Server, where mssql-django drops
# a unique index when an unrelated AlterField retypes a model's primary key; but the
# repair decides per constraint by asking the database what it enforces, so it names no
# engine and is a no-op wherever there is nothing to put back. 1 of these 1 involve a
# nullable column and so need a filtered index, because SQL Server treats NULLs as
# equal where Django does not.
#
# (app_label, model_name, fields, fields that may be NULL)
UNIQUE_REPAIRS = [
    ('units', 'UnitType', ('model', 'name', 'unit_class', 'vendor'), ('model', 'unit_class', 'vendor')),
]


def restore_unique_constraints(apps, schema_editor):
    repair_unique_constraints(apps, schema_editor, UNIQUE_REPAIRS, log=print)


def remove_restored_unique_constraints(apps, schema_editor):
    remove_repaired_constraints(apps, schema_editor, UNIQUE_REPAIRS)


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0021_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Set to false if unit is no longer in use",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="install_date",
            field=models.DateField(
                blank=True,
                help_text="Optional install date",
                null=True,
                verbose_name="install date",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_serviceable",
            field=models.BooleanField(
                default=True,
                help_text="Set to true to enable this unit to be selectable in service events",
                verbose_name="is serviceable",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Optional location information",
                max_length=256,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                help_text="The display name for this unit",
                max_length=256,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A unique number for this unit. Leave blank to have it assigned automatically",
                unique=True,
                verbose_name="number",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Optional serial number",
                max_length=256,
                null=True,
                verbose_name="serial number",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="date_changed",
            field=models.DateField(
                blank=True,
                help_text="Date the units available time changed or will change",
                verbose_name="Date Changed",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_friday",
            field=models.DurationField(
                help_text="Duration of available time on Fridays",
                verbose_name="Hours Friday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_monday",
            field=models.DurationField(
                help_text="Duration of available time on Mondays",
                verbose_name="Hours Monday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_saturday",
            field=models.DurationField(
                help_text="Duration of available time on Saturdays",
                verbose_name="Hours Saturday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_sunday",
            field=models.DurationField(
                help_text="Duration of available time on Sundays",
                verbose_name="Hours Sunday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_thursday",
            field=models.DurationField(
                help_text="Duration of available time on Thursdays",
                verbose_name="Hours Thursday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_tuesday",
            field=models.DurationField(
                help_text="Duration of available time on Tuesdays",
                verbose_name="Hours Tuesday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_wednesday",
            field=models.DurationField(
                help_text="Duration of available time on Wednesdays",
                verbose_name="Hours Wednesday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="units.unit",
                verbose_name="unit",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="date",
            field=models.DateField(
                help_text="Date of available time change", verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="hours",
            field=models.DurationField(
                help_text="New duration of availability", verbose_name="hours"
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A quick name or reason for the change",
                max_length=64,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="units.unit",
                verbose_name="unit",
            ),
        ),
        migrations.RunPython(
            restore_unique_constraints,
            remove_restored_unique_constraints,
        ),
    ]
