# Generated by Django 2.2.18 on 2021-05-17 15:35

from django.db import migrations


def set_default_sites(apps, schema):
    unit = apps.get_model("units", "Unit")
    site = apps.get_model("units", "Site")
    site, __ = site.objects.get_or_create(name="Default Site", slug="default-site")
    unit.objects.filter(site=None).update(site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0021_auto_20210525_1102'),
    ]

    operations = [
        migrations.RunPython(set_default_sites, lambda apps, schema: None)
    ]
