# Generated by Django 2.2.18 on 2021-06-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_add_default_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='site',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to='units.Site'),
        ),
    ]
