# Generated by Django 2.2.18 on 2021-07-06 01:02

from django.db import migrations


def add_default_unit_class(apps, schema):

    UnitClass = apps.get_model("units", "UnitClass")
    UnitType = apps.get_model("units", "UnitType")

    null_class_types = UnitType.objects.filter(unit_class=None)
    if null_class_types:
        default, __ = UnitClass.objects.get_or_create(name="Default")
        null_class_types.update(unit_class=default)


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_auto_20210604_1106'),
    ]

    operations = [
        migrations.RunPython(add_default_unit_class, lambda apps, schema: None),
    ]
