# Generated by Django 2.2.18 on 2021-07-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_default_unit_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AlterField(
            model_name='unittype',
            name='unit_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.UnitClass', verbose_name='unit class'),
        ),
    ]
