# Generated by Django 2.2.18 on 2021-07-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0025_auto_20210705_2117'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Room',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Name of room or room number', max_length=32, verbose_name='name')),
                        ('site', models.ForeignKey(blank=True, help_text='Site this storage room is located', null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Site', verbose_name='site')),
                    ],
                    options={
                        'ordering': ['site', 'name'],
                        'unique_together': {('site', 'name')},
                    },
                ),
                migrations.CreateModel(
                    name='Storage',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('location', models.CharField(blank=True, help_text='Where is this storage located?', max_length=32, null=True, verbose_name='location')),
                        ('description', models.TextField(blank=True, help_text='Optional description of this storage', max_length=255, null=True, verbose_name='description')),
                        ('room', models.ForeignKey(blank=True, help_text='Room for part storage', null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Room', verbose_name='room')),
                    ],
                    options={
                        'verbose_name_plural': 'Storage',
                        'unique_together': {('room', 'location')},
                    },
                ),
            ],
            # note, we already renamed the table in parts_0017
            database_operations=[],
        ),
    ]
