# Generated by Django 2.2.18 on 2021-07-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_default_room_site'),
        ('units', '0026_room_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='site',
            field=models.ForeignKey(help_text='Site this storage room is located', on_delete=django.db.models.deletion.CASCADE, to='units.Site', verbose_name='site'),
        ),
    ]
