# Generated by Django 2.2.18 on 2021-07-06 17:16

from django.db import migrations


def copy_permissions(apps, from_app: str, to_app: str, model: str) -> None:
    """Copy user and group permissions for `from_app.model` to `to_app.model`"""

    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        ct_from = ContentType.objects.get(app_label=from_app, model=model)
    except ContentType.DoesNotExist:
        # initial migration of database so no content type for old parts model
        return

    ct_to = ContentType.objects.get(app_label=to_app, model=model)

    for perm_from in ct_from.permission_set.all():
        perm_to = ct_to.permission_set.get(name=perm_from.name)
        perm_to.group_set.add(*perm_from.group_set.all())
        perm_to.user_set.add(*perm_from.user_set.all())


def copy_permissions_to_units(apps, schema):
    copy_permissions(apps, "parts", "units", "room")
    copy_permissions(apps, "parts", "units", "storage")


def copy_permissions_to_parts(apps, schema):
    copy_permissions(apps, "units", "parts", "room")
    copy_permissions(apps, "units", "parts", "storage")


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0026_room_storage'),
    ]

    operations = [
        migrations.RunPython(copy_permissions_to_units, copy_permissions_to_parts)
    ]
