# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20170505_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuepriority',
            options={'verbose_name_plural': 'Priorities'},
        ),
    ]
