# Generated by Django 1.10.2 on 2017-05-05 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('issue_tracker', '0003_auto_20170505_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuepriority',
            options={'ordering': ['order'], 'verbose_name_plural': 'Priorities'},
        ),
    ]
