# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20170505_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_tags',
            field=models.ManyToManyField(to='issue_tracker.IssueTag'),
        ),
    ]
