# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_issuetag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='error_screen',
            field=models.TextField(blank=True, help_text='Any error screen details. (Note the ability to click "Switch to copy-and-paste view" to copy Traceback)', null=True),
        ),
    ]
