# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_auto_20170505_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_tags',
            field=models.ManyToManyField(help_text='If desired, add multiple tags to this issue', to='issue_tracker.IssueTag'),
        ),
    ]
