# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0010_auto_20170531_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'Statuses'},
        ),
    ]
