# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_auto_20170531_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.ForeignKey(help_text='Current status of this issue', null=True, on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.IssueStatus'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_tags',
            field=models.ManyToManyField(blank=True, help_text='If desired, add multiple tags to this issue', null=True, to='issue_tracker.IssueTag'),
        ),
    ]
