# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0012_auto_20170531_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatus',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
