# Generated by Django 2.1.5 on 2019-01-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('issue_tracker', '0014_auto_20171027_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.ForeignKey(
                help_text='Current status of this issue',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='issue_tracker.IssueStatus',
            ),
        ),
    ]
