# Generated by Django 4.2 on 2025-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_tracker", "0016_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterModelOptions(
            name="issuepriority",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Priority",
                "verbose_name_plural": "Issue Priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="issuestatus",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetag",
            options={
                "ordering": ("name",),
                "verbose_name": "Issue Tag",
                "verbose_name_plural": "Issue Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetype",
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
            },
        ),
        migrations.AlterField(
            model_name="issuetag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
