# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-08 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qafollowup',
            options={'permissions': (('view_qafollowup', 'Can view veturn vo service qa'), ('perform_qafollowup', 'Can perform return to service qa'))},
        ),
    ]
