# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0003_auto_20171204_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceevent',
            name='is_review_required',
            field=models.BooleanField(default=True, help_text='Does this service event require review?'),
        ),
    ]
