# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 17:21
from __future__ import unicode_literals

from django.db import migrations
import qatrack.service_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0007_servicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='extra_info',
            field=qatrack.service_log.models.JSONField(blank=True, null=True),
        ),
    ]
