# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0008_auto_20180403_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelog',
            name='log_type',
            field=models.CharField(choices=[('new_se', 'New Service Event'), ('mod_se', 'Modified Servicew Event'), ('stat_se', 'Service Event Status Changed'), ('rtsqa', 'Changed Return To Service'), ('perf_rts', 'Performed Return To Service'), ('app_rts', 'Approved Return To Service')], max_length=10),
        ),
    ]
