# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-04 17:30
from __future__ import unicode_literals

from django.db import migrations

CREATE_PARTIAL_INDEX = """
    CREATE UNIQUE INDEX hours_notnull_uni_idx ON service_log_hours(service_event_id, third_party_id, user_id)
    WHERE third_party_id IS NOT NULL AND user_id IS NOT NULL;

    CREATE UNIQUE INDEX hours_usernull_uni_idx ON service_log_hours(service_event_id, third_party_id)
    WHERE third_party_id IS NOT NULL AND user_id IS NULL;

    CREATE UNIQUE INDEX hours_tpnull_uni_idx ON service_log_hours(service_event_id, user_id)
    WHERE third_party_id IS NULL AND user_id IS NOT NULL;

    CREATE UNIQUE INDEX hours_bothnull_uni_idx ON service_log_hours(service_event_id)
    WHERE third_party_id IS NULL AND user_id IS NULL;
"""


DROP_PARTIAL_INDEX = """
    DROP INDEX hours_notnull_uni_idx;
    DROP INDEX hours_usernull_uni_idx;
    DROP INDEX hours_tpnull_uni_idx;
    DROP INDEX hours_bothnull_uni_idx;
"""

def forward(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        return
    migrations.RunSQL(CREATE_PARTIAL_INDEX)

def reverse(apps, schema_editor):

    if schema_editor.connection.vendor == 'mysql':
        return

    migrations.RunSQL(DROP_PARTIAL_INDEX)

class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0009_auto_20180411_1644'),
    ]

    operations = [migrations.RunPython(forward, reverse)]
