# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0014_auto_20180601_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceevent',
            name='service_event_related',
            field=models.ManyToManyField(blank=True, help_text='Enter the service event IDs of any related service events.', related_name='_serviceevent_service_event_related_+', to='service_log.ServiceEvent', verbose_name='Related service events'),
        ),
    ]
