# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0015_auto_20180725_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='is_review_required',
            field=models.BooleanField(default=True, help_text='Does this service type require review'),
        ),
    ]
