# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0017_auto_20180814_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceeventstatus',
            name='rts_qa_must_be_reviewed',
            field=models.BooleanField(default=True, help_text='Service events with Return To Service (RTS) QA that has not been reviewed can not have this status selected if set to true.', verbose_name='Return To Service (RTS) QA Must be Reviewed'),
        ),
    ]
