# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0018_auto_20181119_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceeventstatus',
            name='rts_qa_must_be_reviewed',
            field=models.BooleanField(default=True, help_text='Service events with Return To Service (RTS) QC that has not been reviewed can not have this status selected if set to true.', verbose_name='Return To Service (RTS) QC Must be Reviewed'),
        ),
    ]
