# Generated by Django 2.1.7 on 2019-07-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0020_auto_20190129_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='grouplinker',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Allow selecting multiple users when using this group linker', verbose_name='Multiple users'),
        ),
        migrations.AlterField(
            model_name='grouplinker',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select the group. Leave blank to allow choosing any user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='grouplinkerinstance',
            unique_together=set(),
        ),
    ]
