# Generated by Django 2.1.11 on 2019-09-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0022_auto_20190819_1531'),
        ('service_log', '0022_auto_20190903_1336'),
    ]

    operations = [
    ]
