# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_log", "0027_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grouplinker",
            options={
                "verbose_name": "Group Linker",
                "verbose_name_plural": "Group Linkers",
            },
        ),
        migrations.AlterModelOptions(
            name="grouplinkerinstance",
            options={
                "default_permissions": (),
                "verbose_name": "Group Linker Instance",
                "verbose_name_plural": "Group Linker Instances",
            },
        ),
        migrations.AlterModelOptions(
            name="hours",
            options={
                "default_permissions": (),
                "permissions": (("can_have_hours", "Can have hours"),),
                "verbose_name": "Hours",
                "verbose_name_plural": "Hours",
            },
        ),
        migrations.AlterModelOptions(
            name="returntoserviceqa",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ["-datetime_assigned"],
                "permissions": (
                    ("view_returntoserviceqa", "Can view Return To Service QC"),
                    ("perform_returntoserviceqa", "Can perform Return To Service QC"),
                ),
                "verbose_name": "Return To Service QA",
                "verbose_name_plural": "Return To Service QA",
            },
        ),
        migrations.AlterModelOptions(
            name="servicearea",
            options={
                "ordering": ("name",),
                "verbose_name": "service area",
                "verbose_name_plural": "service areas",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceevent",
            options={
                "default_permissions": ("add", "change", "delete"),
                "get_latest_by": "datetime_service",
                "ordering": ["-datetime_service"],
                "permissions": (
                    ("review_serviceevent", "Can review service event"),
                    ("view_serviceevent", "Can review service event"),
                ),
                "verbose_name": "Service Event",
                "verbose_name_plural": "Service Events",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventschedule",
            options={
                "verbose_name": "Service Event Schedule",
                "verbose_name_plural": "Assign Service Event Templates to Units",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventstatus",
            options={
                "ordering": ("order", "pk"),
                "verbose_name": "Service Event Status",
                "verbose_name_plural": "Service Event Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceeventtemplate",
            options={
                "ordering": ("name",),
                "verbose_name": "Service Event Template",
                "verbose_name_plural": "Service Event Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="servicelog",
            options={
                "default_permissions": (),
                "ordering": ("-datetime",),
                "verbose_name": "Service Event Log",
                "verbose_name_plural": "Service Event Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="servicetype",
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
            },
        ),
        migrations.AlterModelOptions(
            name="thirdparty",
            options={
                "verbose_name": "Third Party",
                "verbose_name_plural": "Third Parties",
            },
        ),
        migrations.AlterModelOptions(
            name="unitservicearea",
            options={
                "ordering": ("unit", "service_area"),
                "verbose_name": "Unit Service Area",
                "verbose_name_plural": "Unit Service Area Assignments",
            },
        ),
    ]
