"""Record the outstanding field state for service_log, and repair 5 unique indexes
SQL Server dropped.

Part of one bundled set across seven apps, 195 operations in total, of which 10 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every `AlterField` here is metadata.** `sqlmigrate` renders all 195 of them as
`-- (no-op)` on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine.

**The `RunPython` at the end is the one part that can change a schema.** It adds back
unique constraints the database has stopped enforcing: `mssql-django` drops a unique
index when an unrelated `AlterField` retypes a model's primary key and never recreates
it, which the 4.0 migrations did to every model, so a SQL Server installation silently
stopped enforcing uniqueness these models declare. 5 of this app's constraints are affected, 3 of
them needing a filtered index because SQL Server treats NULLs as equal where Django does
not.

**It names no engine.** Each constraint is repaired only if the database is not
currently enforcing it, so on SQLite, PostgreSQL and MySQL - measured, all three report
nothing to repair - every one is skipped and no DDL is issued. Django generates the SQL
through `schema_editor.add_constraint`, so each backend emits its own syntax rather than
this migration guessing it.

It changes no migration state (the models already declare this uniqueness - the database
is what diverged), and where duplicate rows already exist it reports them and moves on
rather than failing the upgrade. Run `manage.py check_unique_constraints` first to see
whether anything will be skipped.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.conf import settings
from django.db import migrations, models

from qatrack.qatrack_core.unique_repair import (
    remove_repaired_constraints,
    repair_unique_constraints,
)
import django.db.models.deletion



# Unique constraints the database has stopped enforcing - see
# qatrack/qatrack_core/unique_repair.py for the mechanism and why this is a repair
# rather than a state change. In practice this is SQL Server, where mssql-django drops
# a unique index when an unrelated AlterField retypes a model's primary key; but the
# repair decides per constraint by asking the database what it enforces, so it names no
# engine and is a no-op wherever there is nothing to put back. 3 of these 5 involve a
# nullable column and so need a filtered index, because SQL Server treats NULLs as
# equal where Django does not.
#
# (app_label, model_name, fields, fields that may be NULL)
UNIQUE_REPAIRS = [
    ('service_log', 'GroupLinker', ('group', 'name'), ('group',)),
    ('service_log', 'Hours', ('service_event', 'third_party', 'user'), ('third_party', 'user')),
    ('service_log', 'ServiceEventSchedule', ('frequency', 'service_event_template', 'unit_service_area'), ('frequency',)),
    ('service_log', 'ThirdParty', ('first_name', 'last_name', 'vendor'), ()),
    ('service_log', 'UnitServiceArea', ('service_area', 'unit'), ()),
]


def restore_unique_constraints(apps, schema_editor):
    repair_unique_constraints(apps, schema_editor, UNIQUE_REPAIRS, log=print)


def remove_restored_unique_constraints(apps, schema_editor):
    remove_repaired_constraints(apps, schema_editor, UNIQUE_REPAIRS)


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0061_v4_0_2_final"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_log", "0028_v4_0_final"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="returntoserviceqa",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ["-datetime_assigned"],
                "permissions": (
                    ("view_returntoserviceqa", "Can view Return To Service QC"),
                    ("perform_returntoserviceqa", "Can perform Return To Service QC"),
                ),
                "verbose_name": "Return To Service QC",
                "verbose_name_plural": "Return To Service QC",
            },
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="service_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="service_log.serviceevent",
                verbose_name="service event",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="test_list_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtsqa_for_tli",
                to="qa.testlistinstance",
                verbose_name="test list instance",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="unit_test_collection",
            field=models.ForeignKey(
                help_text="Select a TestList to perform",
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.unittestcollection",
                verbose_name="unit test collection",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="user_assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user assigned by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevent",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When was this service event due when it was performed",
                null=True,
                verbose_name="due date",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevent",
            name="include_for_scheduling",
            field=models.BooleanField(
                default=True,
                help_text="Should this instance be considered when calculating due dates?",
                verbose_name="Include for Scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventschedule",
            name="assigned_to",
            field=models.ForeignKey(
                help_text="QC group that this test list should nominally be performed by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serviceeventschedule_assigned_to",
                to="auth.group",
                verbose_name="assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventschedule",
            name="visible_to",
            field=models.ManyToManyField(
                help_text="Select groups who will be able to see this test collection on this unit",
                related_name="serviceeventschedule_visible_to",
                to="auth.group",
                verbose_name="visible to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventtemplate",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.RunPython(
            restore_unique_constraints,
            remove_restored_unique_constraints,
        ),
    ]
