# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Suppliers of this part', related_name='parts', through='parts.PartSupplierCollection', to='parts.Supplier'),
        ),
    ]
