# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20171027_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='alt_part_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_obsolete',
            field=models.BooleanField(default=False, help_text='Is this part now obsolete?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.PartCategory'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity_min',
            field=models.PositiveIntegerField(default=0, help_text='Notify when the quantity of this part in storage falls below this number'),
        ),
    ]
