# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20180327_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['part_number'], 'permissions': (('view_part', 'Can View Part'),)},
        ),
    ]
