# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20180529_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partstoragecollection',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='partsuppliercollection',
            options={'default_permissions': ()},
        ),
    ]
