# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 00:00
from __future__ import unicode_literals
import logging

from django.db import migrations
from django.db.models import F


logger = logging.getLogger("qatrack.migrations")


def copy_description_to_name(apps, schema):

    Part = apps.get_model("parts", "Part")

    for p in Part.objects.all():

        if len(p.description.strip()) > 255:
            msg = "Description of part ID %d: %s will be truncated to 255 characters" % (p.id, p.description)
            print(msg)
            logger.warning(msg)

        p.name = p.description.strip()[:255]
        p.save()


def copy_name_to_description(apps, schema):

    Part = apps.get_model("parts", "Part")
    Part.objects.all().update(description=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_part_name'),
    ]

    operations = [
        migrations.RunPython(copy_description_to_name, copy_name_to_description)
    ]
