# Generated by Django 1.11.13 on 2018-06-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parts', '0008_copy_description_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
    ]
