# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_copy_description_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
    ]
