# Generated by Django 2.1.11 on 2019-12-03 16:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20190129_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='new_or_used',
            field=models.CharField(choices=[('both', 'New & Used'), ('new', 'New'), ('used', 'Used')], default='both', help_text='Select whether this Part is used to track new, used, or both new and used inventory', max_length=12, verbose_name='New or Used'),
        ),
        migrations.AlterField(
            model_name='part',
            name='alt_part_number',
            field=models.CharField(blank=True, help_text='Is this part also identified by a different number?', max_length=32, null=True, verbose_name='Alternate part number'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost of this part', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text='Brief name describing this part', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional comments about this part', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_category',
            field=models.ForeignKey(blank=True, help_text='Select what category this part is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.PartCategory', verbose_name='part category'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(help_text='Enter the part number for this part.', max_length=32, verbose_name='part number'),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity_current',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='The number of parts in storage currently', verbose_name='current quantity'),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity_min',
            field=models.PositiveIntegerField(default=0, help_text='Notify when the quantity of this part in storage falls below this number', verbose_name='Notification level'),
        ),
        migrations.AlterField(
            model_name='part',
            name='storage',
            field=models.ManyToManyField(help_text='Storage locations for this part', related_name='parts', through='parts.PartStorageCollection', to='parts.Storage', verbose_name='storage'),
        ),
        migrations.AlterField(
            model_name='part',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Suppliers of this part', related_name='parts', through='parts.PartSupplierCollection', to='parts.Supplier', verbose_name='suppliers'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='name',
            field=models.CharField(help_text='Enter a name for this part category (e.g. Linac Parts, Table Parts etc)', max_length=64, verbose_name='part category'),
        ),
        migrations.AlterField(
            model_name='partstoragecollection',
            name='part',
            field=models.ForeignKey(help_text='Select the part to be associated with a Storage', on_delete=django.db.models.deletion.CASCADE, to='parts.Part', verbose_name='part'),
        ),
        migrations.AlterField(
            model_name='partstoragecollection',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of parts in this storage', verbose_name='storage'),
        ),
        migrations.AlterField(
            model_name='partstoragecollection',
            name='storage',
            field=models.ForeignKey(help_text='Select the Storage to be associated with this Part', on_delete=django.db.models.deletion.CASCADE, to='parts.Storage', verbose_name='storage'),
        ),
        migrations.AlterField(
            model_name='partsuppliercollection',
            name='part',
            field=models.ForeignKey(help_text='Select the Part to be associated with this Supplier', on_delete=django.db.models.deletion.CASCADE, to='parts.Part', verbose_name='part'),
        ),
        migrations.AlterField(
            model_name='partsuppliercollection',
            name='part_number',
            field=models.CharField(blank=True, help_text='Does this supplier have a different part number for this part', max_length=32, null=True, verbose_name='part number'),
        ),
        migrations.AlterField(
            model_name='partsuppliercollection',
            name='supplier',
            field=models.ForeignKey(help_text='Select the Supplier to be associated with this Part', on_delete=django.db.models.deletion.CASCADE, to='parts.Supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='from_storage',
            field=models.ForeignKey(blank=True, help_text='Select which Storage the parts were taken from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Storage', verbose_name='from storage'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='part',
            field=models.ForeignKey(help_text='Select the part used', on_delete=django.db.models.deletion.CASCADE, to='parts.Part', verbose_name='part'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='quantity',
            field=models.IntegerField(help_text='Select how many parts were used from this Storage', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='service_event',
            field=models.ForeignKey(help_text='Select the Service Event the part was used in', on_delete=django.db.models.deletion.CASCADE, to='service_log.ServiceEvent', verbose_name='service event'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Name of room or room number', max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this storage room is located', null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this storage', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='location',
            field=models.CharField(blank=True, help_text='Where is this storage located?', max_length=32, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room for part storage', null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.Room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Enter a unique name for this supplier', max_length=32, unique=True, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional comments about this supplier', max_length=255, null=True, verbose_name='notes'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('part_number', 'new_or_used')},
        ),
    ]
