# Generated by Django 2.1.11 on 2020-01-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_auto_20191203_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, help_text='Enter the part number for this part.', max_length=32, verbose_name='part number'),
        ),
    ]
