# Generated by Django 2.1.15 on 2020-12-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_auto_20200119_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter this persons first name', max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Enter this persons last name', max_length=64, verbose_name='last name')),
                ('email', models.EmailField(help_text='Enter this persons email address', max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Company phone number', max_length=31, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='Enter a URL for the company', verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='part',
            name='new_or_used',
            field=models.CharField(choices=[('both', 'New & Used'), ('new', 'New'), ('used', 'Used')], default='both', help_text='Is this for tracking inventory of new, used, or both', max_length=12, verbose_name='New or Used'),
        ),
        migrations.AddField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Supplier', verbose_name='supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name', 'supplier')},
        ),
        # migrations.AlterUniqueTogether(
        #     name='partsuppliercollection',
        #     unique_together=None,
        # ),
    ]
