# Generated by Django 2.1.15 on 2020-12-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_auto_20201230_0955'),
        ('parts', '0013_auto_20200418_1958'),
    ]

    operations = [
    ]
