# Generated by Django 2.2.18 on 2021-07-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20210706_0859'),
    ]

    # sqlite can't rename table while in a transaction
    atomic = settings.DATABASES and 'sqlite' not in settings.DATABASES['default']['ENGINE']

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Room',
                ),
                migrations.DeleteModel(
                    name='Storage',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Room',
                    table='units_room',
                ),
                migrations.AlterModelTable(
                    name='Storage',
                    table='units_storage',
                ),
            ]
        ),
    ]
