# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0017_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="part",
            options={
                "ordering": ["part_number"],
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
            },
        ),
        migrations.AlterModelOptions(
            name="partcategory",
            options={
                "verbose_name": "Part Category",
                "verbose_name_plural": "Part Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="partstoragecollection",
            options={
                "default_permissions": (),
                "verbose_name": "Part Storage Collection",
                "verbose_name_plural": "Part Storage Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="partsuppliercollection",
            options={
                "default_permissions": (),
                "verbose_name": "Part Supplier Collection",
                "verbose_name_plural": "Part Supplier Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="partused",
            options={"verbose_name": "Part Used", "verbose_name_plural": "Parts Used"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["site", "name"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={"verbose_name": "Storage", "verbose_name_plural": "Storage"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ("name",),
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
    ]
