"""Record the outstanding field state for parts, and repair 5 unique indexes
SQL Server dropped.

Part of one bundled set across seven apps, 195 operations in total, of which 1 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every `AlterField` here is metadata.** `sqlmigrate` renders all 195 of them as
`-- (no-op)` on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine.

**The `RunPython` at the end is the one part that can change a schema.** It adds back
unique constraints the database has stopped enforcing: `mssql-django` drops a unique
index when an unrelated `AlterField` retypes a model's primary key and never recreates
it, which the 4.0 migrations did to every model, so a SQL Server installation silently
stopped enforcing uniqueness these models declare. 5 of this app's constraints are affected, 2 of
them needing a filtered index because SQL Server treats NULLs as equal where Django does
not.

**It names no engine.** Each constraint is repaired only if the database is not
currently enforcing it, so on SQLite, PostgreSQL and MySQL - measured, all three report
nothing to repair - every one is skipped and no DDL is issued. Django generates the SQL
through `schema_editor.add_constraint`, so each backend emits its own syntax rather than
this migration guessing it.

It changes no migration state (the models already declare this uniqueness - the database
is what diverged), and where duplicate rows already exist it reports them and moves on
rather than failing the upgrade. Run `manage.py check_unique_constraints` first to see
whether anything will be skipped.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.db import migrations, models

from qatrack.qatrack_core.unique_repair import (
    remove_repaired_constraints,
    repair_unique_constraints,
)



# Unique constraints the database has stopped enforcing - see
# qatrack/qatrack_core/unique_repair.py for the mechanism and why this is a repair
# rather than a state change. In practice this is SQL Server, where mssql-django drops
# a unique index when an unrelated AlterField retypes a model's primary key; but the
# repair decides per constraint by asking the database what it enforces, so it names no
# engine and is a no-op wherever there is nothing to put back. 2 of these 5 involve a
# nullable column and so need a filtered index, because SQL Server treats NULLs as
# equal where Django does not.
#
# (app_label, model_name, fields, fields that may be NULL)
UNIQUE_REPAIRS = [
    ('parts', 'Contact', ('first_name', 'last_name', 'supplier'), ()),
    ('parts', 'Part', ('new_or_used', 'part_number'), ()),
    ('parts', 'PartStorageCollection', ('part', 'storage'), ()),
    ('parts', 'Room', ('name', 'site'), ('site',)),
    ('parts', 'Storage', ('location', 'room'), ('location', 'room')),
]


def restore_unique_constraints(apps, schema_editor):
    repair_unique_constraints(apps, schema_editor, UNIQUE_REPAIRS, log=print)


def remove_restored_unique_constraints(apps, schema_editor):
    remove_repaired_constraints(apps, schema_editor, UNIQUE_REPAIRS)


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0018_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="is_obsolete",
            field=models.BooleanField(
                default=False,
                help_text="Is this part now obsolete?",
                verbose_name="Is obsolete",
            ),
        ),
        migrations.RunPython(
            restore_unique_constraints,
            remove_restored_unique_constraints,
        ),
    ]
