# Generated by Django 2.2.18 on 2021-07-08 18:40

from django.db import migrations


def set_default_sites(apps, schema):
    Room = apps.get_model("units", "Room")
    Site = apps.get_model("units", "Site")
    site, __ = Site.objects.get_or_create(name="Default Site", defaults={'slug': "default-site"})
    Room.objects.filter(site=None).update(site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_rename_storage_room_tables'),
    ]

    operations = [
        migrations.RunPython(set_default_sites, lambda apps, schema: None)
    ]
