# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:55
from __future__ import unicode_literals

from django.db import migrations


def set_utc_name(apps, schema_editor):

    UnitTestCollection = apps.get_model('qa', 'UnitTestCollection')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    TestList = apps.get_model('qa', 'TestList')
    TestListCycle = apps.get_model('qa', 'TestListCycle')

    test_list_type = ContentType.objects.get_for_model(TestList)

    for utc in UnitTestCollection.objects.all():

        utc_ct = utc.content_type

        if utc_ct.id == test_list_type.id:
            utc.name = TestList.objects.get(pk=utc.object_id).name
        else:
            utc.name = TestListCycle.objects.get(pk=utc.object_id).name

        utc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_029_to_030_first'),
    ]

    operations = [
        migrations.RunPython(set_utc_name),
    ]
