# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20161218_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittestcollection',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Frequency with which this test list is to be performed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unittestcollections', to='qa.Frequency'),
        ),
    ]
