# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:56
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Permission, Group
from django.db import migrations


def add_in_progress_perm(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    permission = Permission.objects.get(codename="can_save_in_progress")
    for group in Group.objects.all():
        group.permissions.add(permission)


def rem_in_progress_perm(apps, schema_editor):

    Permission.objects.get(codename="can_save_in_progress").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20161218_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testlistinstance',
            options={'get_latest_by': 'work_completed', 'permissions': (('can_override_date', 'Can override date'), ('can_perform_subset', 'Can perform subset of tests'), ('can_view_completed', 'Can view previously completed instances'), ('can_save_in_progress', "Can save test lists as 'In Progress'"))},
        ),
        migrations.RunPython(add_in_progress_perm, rem_in_progress_perm)
    ]
