# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20171103_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(db_index=True, help_text='Name for this test', max_length=255),
        ),
    ]
