# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20171103_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(db_index=True, help_text='Name for this test', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='bool_warning_only',
            field=models.BooleanField(default=False, help_text='Boolean tests not matching references should be considered at tolerance rather than action', verbose_name='Boolean Warning Only'),
        ),
    ]
