# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_sublist_to_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlist',
            name='sublists',
        ),
    ]
