# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_remove_testlist_sublists'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublist',
            name='outline',
            field=models.BooleanField(default=False, help_text='Check to indicate whether sublist tests should be distinguished visually from parent tests'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='order',
            field=models.IntegerField(db_index=True),
        ),
    ]
