# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import re

preset_colours = {
    'not_requires_review': 'rgba(0,166,90,1)',
    'not_valid': 'rgba(221,75,57,1)'
}


def set_default_status_colours(apps, schema):
    TestInstanceStatus = apps.get_model("qa", "TestInstanceStatus")

    for s in TestInstanceStatus.objects.all():
        if not s.valid:
            s.colour = preset_colours['not_valid']
        elif not s.requires_review:
            s.colour = preset_colours['not_requires_review']
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_unittestinfochange'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstancestatus',
            name='colour',
            field=models.CharField(default=settings.DEFAULT_TEST_STATUS_COLOUR, max_length=22, validators=[django.core.validators.RegexValidator(re.compile('^rgba\\(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),(0(\\.[0-9][0-9]?)?|1)\\)$', 32), 'Enter a valid color.', 'invalid')]),
        ),
        migrations.RunPython(set_default_status_colours)
    ]
