# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_testinstancestatus_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreviewrule',
            name='pass_fail',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('ok', 'OK'), ('tolerance', 'Tolerance'), ('action', 'Action'), ('no_tol', 'No Tol Set')], help_text='Pass fail state of test instances to apply this rule to.', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='autoreviewrule',
            name='status',
            field=models.ForeignKey(help_text='Status to assign test instance based on its pass/fail state', on_delete=django.db.models.deletion.CASCADE, to='qa.TestInstanceStatus'),
        ),
        migrations.AlterField(
            model_name='testlistcycle',
            name='day_option_text',
            field=models.CharField(choices=[('day', 'Day'), ('tlname', 'Test List Name')], default='day', help_text='Should the drop down show the day number or test list name?', max_length=8),
        ),
        migrations.AlterField(
            model_name='testlistcycle',
            name='drop_down_label',
            field=models.CharField(default='Choose Day', help_text='Text to be shown alongside the drop down list for selecting the cycle day to perform.', max_length=128),
        ),
    ]
