# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_convert_file_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='testlistmembership',
            options={'default_permissions': (), 'ordering': ('order',)},
        ),
    ]
