# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 17:42
from __future__ import unicode_literals

from django.db import migrations

from qatrack.qa.models import get_tolerance_name, Tolerance as Tolerance_


def set_name(apps, schema_migrations):

    Tolerance = apps.get_model("qa", "Tolerance")
    Tolerance.pass_choices = Tolerance_.pass_choices
    Tolerance.tol_choices = Tolerance_.tol_choices
    for t in Tolerance.objects.all():
        t.name = get_tolerance_name(t)
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0016_tolerance_name'),
    ]

    operations = [
        migrations.RunPython(set_name, lambda apps, schema_migrations: None)
    ]
