# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


def remove_duplicate_tolerances(apps, schema):

    Tolerance = apps.get_model('qa', 'Tolerance')
    TestInstance = apps.get_model('qa', 'TestInstance')
    UnitTestInfoChange = apps.get_model('qa', 'UnitTestInfoChange')
    UnitTestInfo = apps.get_model('qa', 'UnitTestInfo')

    duplicates = Tolerance.objects.order_by(
        *Tolerance._meta.ordering,
    ).values('name').annotate(name_count=models.Count('name')).filter(name_count__gt=1)

    for d in duplicates:
        tolerances = Tolerance.objects.filter(name=d['name'])

        tol_keep = tolerances.first()
        tolerances = tolerances.exclude(id=tol_keep.id)
        ids_change = [t.id for t in tolerances]
        for ti in TestInstance.objects.filter(tolerance_id__in=ids_change):
            ti.tolerance = tol_keep
            ti.save()

        for utic in UnitTestInfoChange.objects.filter(tolerance_id__in=ids_change):
            utic.tolerance = tol_keep
            utic.save()

        for uti in UnitTestInfo.objects.filter(tolerance_id__in=ids_change):
            uti.tolerance = tol_keep
            uti.save()

        tolerances.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_set_tolerance_names'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_tolerances),
    ]
