# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0018_unique_tolerance_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolerance',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
