# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 18:19
from __future__ import unicode_literals

import ast
import logging

from django.db import migrations

logger = logging.getLogger("qatrack.migrations")


def check_calcs(apps, schema):
    from qatrack.qa.models import CALCULATED_TYPES

    Test = apps.get_model("qa", "Test")

    for t in Test.objects.filter(type__in=CALCULATED_TYPES):
        try:
            ast.parse(t.calculation_procedure)
        except:
            msg = (
                "The calculation procedure of the test named '%s' with ID=%d "
                "needs to be updated to be compatible with Python 3."
            ) % (t.name, t.id)
            logger.info(msg)



class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0020_auto_20180924_2313'),
    ]

    operations = [
        migrations.RunPython(check_calcs, lambda apps, schema: None)
    ]
