# Generated by Django 1.11.15 on 2018-11-20 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('qa', '0023_set_recurrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='due_interval',
        ),
    ]
