# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0024_remove_frequency_due_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='window_end',
            field=models.PositiveIntegerField(default=0, help_text='Number of days after a Test List is due that its QC Window ends. After the QC window ends the Test List will be shown as overdue.(Use 0 if it should show as overdue the day after it is due)', verbose_name='QC Window End'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequency',
            name='window_start',
            field=models.PositiveIntegerField(blank=True, help_text="Number of days before a Test List is due that its QC Window starts. QC performed prior to the QC window start will not cause a change in due date. Leave blank to use the classical 'offset' method where the due date is advanced every time QC is performed", null=True, verbose_name='QC Window Start'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='overdue_interval',
            field=models.PositiveIntegerField(help_text='How many days after the due date should a test with this frequency be shown as overdue. (Use 0 if it should show as overdue the day after it is due)'),
        ),
    ]
