# Generated by Django 1.11.15 on 2018-11-29 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('qa', '0026_copy_overdue_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='overdue_interval',
        ),
    ]
