# Generated by Django 2.1.5 on 2019-01-30 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0029_auto_20181217_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='tolerance',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.Tolerance'),
        ),
        migrations.AlterField(
            model_name='testlistinstance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_list_instance_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unittestcollection',
            name='assigned_to',
            field=models.ForeignKey(help_text='QC group that this test list should nominally be performed by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='unittestcollection',
            name='content_type',
            field=models.ForeignKey(help_text='Choose whether to use a Test List or Test List Cycle', limit_choices_to=models.Q(models.Q(('app_label', 'qa'), ('model', 'testlist')), models.Q(('app_label', 'qa'), ('model', 'testlistcycle')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Test List or Test List Cycle'),
        ),
        migrations.AlterField(
            model_name='unittestcollection',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Frequency with which this test list is to be performed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unittestcollections', to='qa.Frequency'),
        ),
        migrations.AlterField(
            model_name='unittestcollection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
        migrations.AlterField(
            model_name='unittestinfochange',
            name='changed_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unittestinfochange',
            name='unit_test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.UnitTestInfo'),
        ),
    ]
