# Generated by Django 2.1.7 on 2019-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0032_auto_20190313_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='formatting',
            field=models.CharField(blank=True, default='', help_text="Format string for numerical results. Use e.g. 2F  to display as fixed precision with 2 decimal places, or 3E to show as scientific format with 3 significant figures, or 4G to use 'general' formatting with up to 4 significant figures.", max_length=10),
        ),
    ]
