# Generated by Django 2.1.7 on 2019-08-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0035_remove_sql_reports_perms'),
        ('qa', '0034_auto_20190805_1248'),
    ]

    operations = [
    ]
