# Generated by Django 2.1.11 on 2019-10-09 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0036_merge_20190805_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('simple', 'Simple Numerical'), ('multchoice', 'Multiple Choice'), ('constant', 'Constant'), ('composite', 'Composite'), ('date', 'Date'), ('datetime', 'Date & Time'), ('string', 'String'), ('scomposite', 'String Composite/JSON'), ('upload', 'File Upload')], default='simple', help_text='Indicate if this test is a Boolean,Simple Numerical,Multiple Choice,Constant,Composite,Date,Date & Time,String,String Composite/Json,File Upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='work_completed',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Format DD MMM YYYY hh:mm (hh:mm is 24h time e.g. 31 May 2012 14:30)'),
        ),
        migrations.AlterField(
            model_name='testlist',
            name='warning_message',
            field=models.CharField(blank=True, default='Do not treat', help_text='Message given when a test value is out of tolerance.  Leave blank to disable warnings from being shown when tests are out of tolerance.', max_length=255),
        ),
    ]
