# Generated by Django 2.1.11 on 2019-10-16 17:45

from django.db import migrations


def add_default_autoreviewruleset(apps, schema):

    AutoReviewRule = apps.get_model("qa", "AutoReviewRule")
    rules = list(AutoReviewRule.objects.all())
    if not rules:
        return

    AutoReviewRuleSet = apps.get_model("qa", "AutoReviewRuleSet")
    ruleset = AutoReviewRuleSet.objects.create(name="Default", is_default=True)
    for rule in rules:
        ruleset.rules.add(rule)

    Test = apps.get_model("qa", "Test")
    Test.objects.filter(auto_review=True).update(autoreviewruleset=ruleset)


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0039_auto_20191016_1401'),
    ]

    operations = [
        migrations.RunPython(add_default_autoreviewruleset, lambda apps, schema: None)
    ]
