# Generated by Django 2.1.11 on 2019-11-21 18:41

from django.db import migrations
from django.db.models import F


def rebuild(apps, schema):

    Category = apps.get_model("qa", "Category")
    Category.objects.update(tree_id=F("id"))
    for cat in Category.objects.all():
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0043_category_tree'),
    ]

    operations = [
        migrations.RunPython(rebuild, lambda a, schema: None),
    ]
