# Generated by Django 2.1.11 on 2019-12-17 00:47

import logging

from django.db import migrations

logger = logging.getLogger("qatrack.migrations")


def update_string_values(apps, schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0046_datestrings_to_dates'),
    ]

    operations = [
        migrations.RunPython(update_string_values, lambda apps, schema: None),
    ]
