# Generated by Django 2.1.11 on 2019-12-17 00:47

from django.db import migrations

import logging

logger = logging.getLogger("qatrack.migrations")


def update_string_values(apps, schema):

    TestInstance = apps.get_model("qa", "TestInstance")

    for ti in TestInstance.objects.filter(unit_test_info__test__type="upload", string_value__startswith="{"):
        attachments = ti.attachment_set.filter(comment__startswith="Uploaded ")
        attachment_ids = ','.join(map(str, attachments.values_list("id", flat=True)))

        logger.warning(
            "0047: Updating Test instance: %d, Test List Instance %d, Attachment IDs: %s, "
            "Old String Value: %s, New String Value: %s" % (ti.id, ti.test_list_instance_id, attachment_ids, ti.string_value, attachment_ids,)
        )

        TestInstance.objects.filter(pk=ti.pk).update(string_value=attachment_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0046_datestrings_to_dates'),
    ]

    operations = [
        migrations.RunPython(update_string_values, lambda apps, schema: None),
    ]
