# Generated by Django 2.1.11 on 2020-01-02 18:58

import logging

from django.db import migrations
from django.db.models import Q

logger = logging.getLogger("qatrack.migrations")


def convert_instances(apps, schema):

    TestInstance = apps.get_model("qa", "TestInstance")

    # get test instances which have json results rather than attachment ids
    tis = TestInstance.objects.filter(
        unit_test_info__test__type="upload",
    ).filter(Q(string_value__startswith="{") | Q(string_value__startswith="["))

    for ti in tis:

        attachment = ti.attachment_set.order_by("pk").first()

        if attachment:
            logger.info(
                "Updating test instance %s (attachment_id=%s) from string_value=%s to string_value=%s json_value=%s" % (
                    ti.id, attachment.id, ti.string_value, attachment.id, ti.string_value
                )
            )

            # set json
            TestInstance.objects.filter(pk=ti.pk).update(
                json_value=ti.string_value,
                string_value=str(attachment.id),
            )
        else:
            logger.info("Unable to find attachment for test instance %d" % ti.id)


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0048_auto_20200102_1356'),
    ]

    operations = [
        migrations.RunPython(convert_instances, lambda apps, schema: None),
    ]
