# Generated by Django 2.1.11 on 2020-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0050_auto_20200131_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='wrap_high',
            field=models.FloatField(blank=True, help_text='Maximum value at which test wraps around to minimum value', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='wrap_low',
            field=models.FloatField(blank=True, help_text='Minimum value at which test wraps around to maximum value', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('simple', 'Simple Numerical'), ('wraparound', 'Wraparound'), ('multchoice', 'Multiple Choice'), ('constant', 'Constant'), ('composite', 'Composite'), ('date', 'Date'), ('datetime', 'Date & Time'), ('string', 'String'), ('scomposite', 'String Composite/JSON'), ('upload', 'File Upload')], default='simple', help_text='Indicate if this test is a Boolean,Simple Numerical,Wraparound,Multiple Choice,Constant,Composite,Date,Date & Time,String,String Composite/Json,File Upload', max_length=10),
        ),
    ]
