# Generated by Django 2.1.15 on 2020-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0052_auto_20200302_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlist',
            name='test_lists',
            field=models.ManyToManyField(blank=True, help_text='Which test lists does this list contain', through='qa.Sublist', to='qa.TestList'),
        ),
    ]
