# Generated by Django 2.1.15 on 2020-06-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0053_testlist_test_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlistinstance',
            name='include_for_scheduling',
            field=models.BooleanField(default=True, help_text='Should this instance be considered when calculating due dates?'),
        ),
    ]
