# Generated by Django 2.1.15 on 2020-06-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0054_testlistinstance_include_for_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='require_comment',
            field=models.BooleanField(default=False, help_text='Require users to enter a comment when submitting this test.', verbose_name='Require Comment'),
        ),
    ]
