# Generated by Django 2.1.15 on 2020-08-12 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qatrack.qatrack_core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0055_test_require_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_started', models.DateTimeField(null=True)),
                ('work_completed', models.DateTimeField(null=True)),
                ('day', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', qatrack.qatrack_core.fields.JSONField(blank=True, help_text='Currently used to store results of upload file analysis. Allows you to retrieve results of file upload analysis without having to reanalyze the file')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='autosave_modifier', to=settings.AUTH_USER_MODEL)),
                ('test_list', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='qa.TestList')),
                ('unit_test_collection', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='qa.UnitTestCollection')),
            ],
        ),
    ]
