# Generated by Django 2.1.15 on 2020-08-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0056_autosave'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosave',
            name='test_list_instance',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.TestListInstance', verbose_name='Test List Instance'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='test_list',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='qa.TestList', verbose_name='Test List'),
        ),
    ]
