# Generated by Django 2.2.18 on 2021-12-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestInstanceStatus',
            new_name='ReviewStatus',
        ),
        migrations.AlterModelOptions(
            name='reviewstatus',
            options={'verbose_name_plural': 'review statuses'},
        ),
    ]
