# Generated by Django 2.2.18 on 2021-06-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='default_reference',
            field=models.ForeignKey(blank=True, help_text='Select a default reference value for this test.  This will not affect any existing references and you will still be able to set per unit reference values later.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.Reference', verbose_name='Default Reference'),
        ),
        migrations.AddField(
            model_name='test',
            name='default_tolerance',
            field=models.ForeignKey(blank=True, help_text='Select a default tolerance for this test.  This will not affect any existing references and you will still be able to set per unit tolerances values later.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.Tolerance', verbose_name='Default Tolerance'),
        ),
    ]
