# Generated by Django 2.2.18 on 2021-12-23 18:27

from django.db import migrations
from django.db import connections

is_sql_lite = 'sqlite' in connections._databases['default']['ENGINE']

class Migration(migrations.Migration):

    atomic=not is_sql_lite  # sqlite can't rename a table in a transaction

    dependencies = [
        ('qa', '0058_testlistinstance_user_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestInstanceStatus',
            new_name='ReviewStatus',
        ),
        migrations.AlterModelOptions(
            name='reviewstatus',
            options={'verbose_name_plural': 'review statuses'},
        ),
    ]
