# Generated by Django 2.2.18 on 2021-12-23 19:57

from django.db import migrations, models
import django.db.models.deletion
import qatrack.qa.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0059_auto_20211223_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlistinstance',
            name='review_status',
            field=models.ForeignKey(default=qatrack.qa.models.ReviewStatus.objects.default_pk, help_text='Select the review status of this test list instance', on_delete=django.db.models.deletion.PROTECT, to='qa.ReviewStatus', verbose_name='Review Status'),
        ),
    ]
