# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0059_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autoreviewrule",
            options={
                "verbose_name": "Auto Review Rule",
                "verbose_name_plural": "Auto Review Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="autoreviewruleset",
            options={
                "verbose_name": "Auto Review Rule Set",
                "verbose_name_plural": "Auto Review Rule Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="autosave",
            options={"verbose_name": "Auto Save", "verbose_name_plural": "Auto Saves"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="frequency",
            options={
                "ordering": ("nominal_interval",),
                "permissions": (("can_choose_frequency", "Choose QC by Frequency"),),
                "verbose_name": "Frequency",
                "verbose_name_plural": "Frequencies",
            },
        ),
        migrations.AlterModelOptions(
            name="reference",
            options={
                "ordering": ["type", "name"],
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
            },
        ),
        migrations.AlterModelOptions(
            name="sublist",
            options={
                "ordering": ("order",),
                "verbose_name": "Sublist",
                "verbose_name_plural": "Sublists",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ("name",),
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
            },
        ),
        migrations.AlterModelOptions(
            name="testinstance",
            options={
                "get_latest_by": "work_completed",
                "permissions": (
                    ("can_view_history", "Can see test history when performing QC"),
                    ("can_view_charts", "Can view charts of test history"),
                    ("can_review", "Can review & approve tests"),
                    ("can_skip_without_comment", "Can skip tests without comment"),
                    (
                        "can_review_own_tests",
                        "Can review & approve  self-performed tests",
                    ),
                ),
                "verbose_name": "Test Instance",
                "verbose_name_plural": "Test Instances",
            },
        ),
        migrations.AlterModelOptions(
            name="testinstancestatus",
            options={
                "verbose_name": "Test Instance Status",
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="testlist",
            options={"ordering": ("name",), "verbose_name_plural": "Test Lists"},
        ),
        migrations.AlterModelOptions(
            name="testlistcycle",
            options={"ordering": ("name",), "verbose_name_plural": "Test List Cycles"},
        ),
        migrations.AlterModelOptions(
            name="testlistcyclemembership",
            options={
                "ordering": ("order",),
                "verbose_name": "Test List Cycle Membership",
                "verbose_name_plural": "Test List Cycle Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="testlistinstance",
            options={
                "get_latest_by": "work_completed",
                "permissions": (
                    ("can_override_date", "Can override date"),
                    ("can_perform_subset", "Can perform subset of tests"),
                    ("can_view_completed", "Can view previously completed instances"),
                    ("can_save_in_progress", "Can save test lists as 'In Progress'"),
                ),
                "verbose_name_plural": "Test List Instances",
            },
        ),
        migrations.AlterModelOptions(
            name="testlistmembership",
            options={
                "ordering": ("order",),
                "verbose_name": "Test List Membership",
                "verbose_name_plural": "Test List Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="tolerance",
            options={
                "ordering": ["type", "act_low", "tol_low", "tol_high", "act_high"],
                "verbose_name": "Tolerance",
                "verbose_name_plural": "Tolerances",
            },
        ),
        migrations.AlterModelOptions(
            name="unittestinfo",
            options={
                "permissions": (("can_view_ref_tol", "Can view Refs and Tols"),),
                "verbose_name": "Set References & Tolerances",
                "verbose_name_plural": "Set References & Tolerances",
            },
        ),
        migrations.AlterModelOptions(
            name="unittestinfochange",
            options={
                "verbose_name": "Unit Test Info Change",
                "verbose_name_plural": "Unit Test Info Changes",
            },
        ),
    ]
