"""Record the outstanding field state for qa, and repair 5 unique indexes
SQL Server dropped.

Part of one bundled set across seven apps, 195 operations in total, of which 132 are
here. `makemigrations` has reported these on a clean checkout of develop for a long
time: the localisation work **added** `verbose_name` labels to fields that had none,
and the resulting field state was never recorded. (Wrapping an existing string in
`gettext_lazy` is *not* what caused this - a lazy proxy compares equal to its resolved
string, so the autodetector cannot see it. Verified on a clean checkout: wrapping three
`help_text` strings in `issue_tracker` produces no migration at all.) 194 of the
operations below carry a `verbose_name`; the remaining one is a `Meta.options` change.

**Every `AlterField` here is metadata.** `sqlmigrate` renders all 195 of them as
`-- (no-op)` on SQLite, PostgreSQL 15 and SQL Server 2022 - no DDL on any engine.

**The `RunPython` at the end is the one part that can change a schema.** It adds back
unique constraints the database has stopped enforcing: `mssql-django` drops a unique
index when an unrelated `AlterField` retypes a model's primary key and never recreates
it, which the 4.0 migrations did to every model, so a SQL Server installation silently
stopped enforcing uniqueness these models declare. 5 of this app's constraints are affected, 2 of
them needing a filtered index because SQL Server treats NULLs as equal where Django does
not.

**It names no engine.** Each constraint is repaired only if the database is not
currently enforcing it, so on SQLite, PostgreSQL and MySQL - measured, all three report
nothing to repair - every one is skipped and no DDL is issued. Django generates the SQL
through `schema_editor.add_constraint`, so each backend emits its own syntax rather than
this migration guessing it.

It changes no migration state (the models already declare this uniqueness - the database
is what diverged), and where duplicate rows already exist it reports them and moves on
rather than failing the upgrade. Run `manage.py check_unique_constraints` first to see
whether anything will be skipped.

The point is not the field state itself but `makemigrations --check`, which the pull
request template asks every contributor to run. With these outstanding it fails on
every install, so it cannot distinguish a contributor's own missing migration from the
inherited backlog - a real schema change would pass unnoticed. With them recorded the
check is a live gate again.
"""

# Generated by Django 4.2.30 on 2026-10-01 05:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models

from qatrack.qatrack_core.unique_repair import (
    remove_repaired_constraints,
    repair_unique_constraints,
)
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import qatrack.qatrack_core.fields
import re



# Unique constraints the database has stopped enforcing - see
# qatrack/qatrack_core/unique_repair.py for the mechanism and why this is a repair
# rather than a state change. In practice this is SQL Server, where mssql-django drops
# a unique index when an unrelated AlterField retypes a model's primary key; but the
# repair decides per constraint by asking the database what it enforces, so it names no
# engine and is a no-op wherever there is nothing to put back. 2 of these 5 involve a
# nullable column and so need a filtered index, because SQL Server treats NULLs as
# equal where Django does not.
#
# (app_label, model_name, fields, fields that may be NULL)
UNIQUE_REPAIRS = [
    ('qa', 'Sublist', ('child', 'parent'), ()),
    ('qa', 'TestListInstance', ('user_key',), ('user_key',)),
    ('qa', 'TestListMembership', ('test', 'test_list'), ()),
    ('qa', 'UnitTestCollection', ('content_type', 'frequency', 'object_id', 'unit'), ('frequency',)),
    ('qa', 'UnitTestInfo', ('test', 'unit'), ()),
]


def restore_unique_constraints(apps, schema_editor):
    repair_unique_constraints(apps, schema_editor, UNIQUE_REPAIRS, log=print)


def remove_restored_unique_constraints(apps, schema_editor):
    remove_repaired_constraints(apps, schema_editor, UNIQUE_REPAIRS)


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0022_v4_0_2_final"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("qa", "0060_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoreviewrule",
            name="pass_fail",
            field=models.CharField(
                choices=[
                    ("not_done", "Not Done"),
                    ("ok", "OK"),
                    ("tolerance", "Tolerance"),
                    ("action", "Action"),
                    ("no_tol", "No Tol Set"),
                ],
                help_text="Pass fail state of test instances to apply this rule to.",
                max_length=15,
                verbose_name="Pass Fail",
            ),
        ),
        migrations.AlterField(
            model_name="autoreviewrule",
            name="status",
            field=models.ForeignKey(
                help_text="Status to assign test instance based on its pass/fail state",
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testinstancestatus",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Give a brief description of what type of tests should be included in this grouping",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="qa.category",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier made of lowercase characters and underscores",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="frequency",
            name="name",
            field=models.CharField(
                help_text="Display name for this frequency",
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="frequency",
            name="nominal_interval",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Nominal number of days between test completions (for internal ordering purposes)",
                verbose_name="Normal Interval",
            ),
        ),
        migrations.AlterField(
            model_name="frequency",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier made of lowercase characters and underscores for this frequency",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reference_creators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reference_modifiers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="name",
            field=models.CharField(
                help_text="Enter a short name for this reference",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="type",
            field=models.CharField(
                choices=[("numerical", "Numerical"), ("boolean", "Yes / No")],
                default="numerical",
                max_length=15,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="value",
            field=models.FloatField(
                help_text="Enter the reference value for this test.",
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="sublist",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlist",
                verbose_name="Child",
            ),
        ),
        migrations.AlterField(
            model_name="sublist",
            name="order",
            field=models.IntegerField(db_index=True, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="sublist",
            name="outline",
            field=models.BooleanField(
                default=False,
                help_text="Check to indicate whether sublist tests should be distinguished visually from parent tests",
                verbose_name="Outline",
            ),
        ),
        migrations.AlterField(
            model_name="sublist",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="qa.testlist",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="calculation_procedure",
            field=models.TextField(
                blank=True,
                help_text="For composite, string composite, and upload tests, enter a Python snippet for evaluation of this test.<br/>For other test types, you may enter a Python snippet to set the initial value of this test.  For example, if you want to set an initial default value of 123 that a user can override for a numerical test, you would set your calculation procedure to:<br/><pre>your_test = 123</pre>To set an initial multiple choice value you would use:<pre>your_test = 'some choice'</pre>To set an initial Boolean value you would use:<pre>your_test = True # or False</pre>",
                null=True,
                verbose_name="Calculation Procedure",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="category",
            field=models.ForeignKey(
                help_text="Choose a category for this test",
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="choices",
            field=models.CharField(
                blank=True,
                help_text="Comma seperated list of choices for multiple choice test types",
                max_length=2048,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="constant_value",
            field=models.FloatField(
                blank=True,
                help_text="Only required for constant value types",
                null=True,
                verbose_name="Constant Value",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="formatting",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Python style string format for numerical results. Leave blank for the QATrack+ default, select one of the predefined options, or enter your own formatting string. <br/>Use e.g. %.2F to display as fixed precision with 2 decimal places, or %.3E to show as scientific format with 3 significant figures, or %.4G to use 'general' formatting with up to 4 significant figures.<br/>You may also use new style Python string formatting (e.g. {:06.2f}).",
                max_length=10,
                verbose_name="Formatting",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="test",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="procedure",
            field=models.CharField(
                blank=True,
                help_text="Link to document describing how to perform this test",
                max_length=512,
                null=True,
                verbose_name="Procedure",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="type",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean"),
                    ("simple", "Simple Numerical"),
                    ("wraparound", "Wraparound"),
                    ("multchoice", "Multiple Choice"),
                    ("constant", "Constant"),
                    ("composite", "Composite"),
                    ("date", "Date"),
                    ("datetime", "Date & Time"),
                    ("string", "String"),
                    ("scomposite", "String Composite/JSON"),
                    ("upload", "File Upload"),
                ],
                default="simple",
                help_text="Indicate if this test is a Boolean,Simple Numerical,Wraparound,Multiple Choice,Constant,Composite,Date,Date & Time,String,String Composite/Json,File Upload",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="wrap_high",
            field=models.FloatField(
                blank=True,
                help_text="Maximum value at which test wraps around to minimum value",
                null=True,
                verbose_name="Wrap High",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="wrap_low",
            field=models.FloatField(
                blank=True,
                help_text="Minimum value at which test wraps around to maximum value",
                null=True,
                verbose_name="Wrap Low",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Add a comment to this test",
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_instance_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="date_value",
            field=models.DateField(blank=True, null=True, verbose_name="Date Value"),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="datetime_value",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Datetime Value"
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="json_value",
            field=qatrack.qatrack_core.fields.JSONField(
                blank=True,
                help_text="Currently used to store results of upload file analysis. Allows you to retrieve results of file upload analysis without having to reanalyze the file",
                null=True,
                verbose_name="JSON Value",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_instance_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="pass_fail",
            field=models.CharField(
                choices=[
                    ("not_done", "Not Done"),
                    ("ok", "OK"),
                    ("tolerance", "Tolerance"),
                    ("action", "Action"),
                    ("no_tol", "No Tol Set"),
                ],
                db_index=True,
                editable=False,
                max_length=20,
                verbose_name="Pass Fail",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.reference",
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="review_date",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Review Date"
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="skipped",
            field=models.BooleanField(
                default=False,
                help_text="Was this test skipped for some reason (add comment)",
                verbose_name="Skipped",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.testinstancestatus",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="string_value",
            field=models.TextField(blank=True, null=True, verbose_name="String Value"),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="test_list_instance",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlistinstance",
                verbose_name="Test List Instance",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="tolerance",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.tolerance",
                verbose_name="Tolerance",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="unit_test_info",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.unittestinfo",
                verbose_name="Unit Test Info",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="value",
            field=models.FloatField(
                help_text="For boolean Tests a value of 0 equals False and any non zero equals True",
                null=True,
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="work_completed",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Work Completed",
            ),
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="work_started",
            field=models.DateTimeField(
                db_index=True, editable=False, verbose_name="Work Started"
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="colour",
            field=models.CharField(
                default="rgba(243,156,18,1)",
                max_length=22,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^rgba\\(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]),(0(\\.[0-9][0-9]?)?|1)\\)$"
                        ),
                        "Enter a valid color.",
                        "invalid",
                    )
                ],
                verbose_name="Colour",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Give a brief description of what type of test results should be given this status",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="export_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Check to indicate whether tests with this status should be exported by default (e.g. for graphing/control charts)",
                verbose_name="Export By Default",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Check to make this status the default for new Test Instances",
                verbose_name="Is Default",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="name",
            field=models.CharField(
                help_text="Display name for this status type",
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="requires_review",
            field=models.BooleanField(
                default=True,
                help_text="Check to indicate that Test Instances with this status require further review",
                verbose_name="Requires Review",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier made of lowercase characters and underscores for this status",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="testinstancestatus",
            name="valid",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, data with this status will not be exported and the TestInstance will not be considered a valid completed Test",
                verbose_name="Valid",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A concise description of this test checklist. (You may use HTML markup)",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="javascript",
            field=models.TextField(
                blank=True,
                help_text="Any extra javascript to run when loading perform page",
                null=True,
                verbose_name="JavaScript",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="slug",
            field=models.SlugField(
                help_text="A short unique name for use in the URL of this list",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="test_lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which test lists does this list contain",
                through="qa.Sublist",
                to="qa.testlist",
                verbose_name="Test Lists",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="tests",
            field=models.ManyToManyField(
                help_text="Which tests does this list contain",
                through="qa.TestListMembership",
                to="qa.test",
                verbose_name="Tests",
            ),
        ),
        migrations.AlterField(
            model_name="testlist",
            name="warning_message",
            field=models.CharField(
                blank=True,
                default="Do not treat",
                help_text="Message given when a test value is out of tolerance.  Leave blank to disable warnings from being shown when tests are out of tolerance.",
                max_length=255,
                verbose_name="Warning Message",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A concise description of this test checklist. (You may use HTML markup)",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="javascript",
            field=models.TextField(
                blank=True,
                help_text="Any extra javascript to run when loading perform page",
                null=True,
                verbose_name="JavaScript",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="slug",
            field=models.SlugField(
                help_text="A short unique name for use in the URL of this list",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcycle",
            name="test_lists",
            field=models.ManyToManyField(
                through="qa.TestListCycleMembership",
                to="qa.testlist",
                verbose_name="Test Lists",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcyclemembership",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlistcycle",
                verbose_name="Cycle",
            ),
        ),
        migrations.AlterField(
            model_name="testlistcyclemembership",
            name="order",
            field=models.IntegerField(verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="testlistcyclemembership",
            name="test_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlist",
                verbose_name="Test List",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="all_reviewed",
            field=models.BooleanField(default=False, verbose_name="All Reviewed"),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_list_instance_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="day",
            field=models.IntegerField(default=0, verbose_name="Day"),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When was this session due when it was performed",
                null=True,
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="flagged",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Used in cooperation with Boolean Tests to highlight this TestListInstance",
                verbose_name="Flagged",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="in_progress",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Mark this session as still in progress so you can complete later (will not be submitted for review)",
                verbose_name="In Progress",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="include_for_scheduling",
            field=models.BooleanField(
                default=True,
                help_text="Should this instance be considered when calculating due dates?",
                verbose_name="Include for Scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="modified",
            field=models.DateTimeField(verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_list_instance_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="reviewed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reviewed"),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_list_instance_reviewer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="test_list",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.testlist",
                verbose_name="Test List",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="unit_test_collection",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.unittestcollection",
                verbose_name="Unit Test Collection",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="user_key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Optional field that can be used to ensure uniqueness when posting results via the API",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="User Key",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="work_completed",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Work Completed",
            ),
        ),
        migrations.AlterField(
            model_name="testlistinstance",
            name="work_started",
            field=models.DateTimeField(db_index=True, verbose_name="Work Started"),
        ),
        migrations.AlterField(
            model_name="testlistmembership",
            name="order",
            field=models.IntegerField(db_index=True, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="testlistmembership",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.test",
                verbose_name="Test",
            ),
        ),
        migrations.AlterField(
            model_name="testlistmembership",
            name="test_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.testlist",
                verbose_name="Test List",
            ),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tolerance_creators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created Date"),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tolerance_modifiers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified Date"),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="name",
            field=models.CharField(
                editable=False, max_length=255, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="tolerance",
            name="type",
            field=models.CharField(
                choices=[
                    ("absolute", "Absolute"),
                    ("percent", "Percentage"),
                    ("multchoice", "Multiple Choice"),
                ],
                help_text="Select whether this will be an absolute or relative tolerance criteria",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Uncheck to disable this test on this unit",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="assigned_to",
            field=models.ForeignKey(
                help_text="QC group that this test list should nominally be performed by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="auto_schedule",
            field=models.BooleanField(
                default=True,
                help_text="If this is checked, due_date will be auto set based on the assigned frequency",
                verbose_name="Auto Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Next time this item is due",
                null=True,
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                help_text="Frequency with which this test list is to be performed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unittestcollections",
                to="qa.frequency",
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="last_instance",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qa.testlistinstance",
                verbose_name="Last Instance",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="name",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="units.unit",
                verbose_name="Unit",
            ),
        ),
        migrations.AlterField(
            model_name="unittestcollection",
            name="visible_to",
            field=models.ManyToManyField(
                help_text="Select groups who will be able to see this test collection on this unit",
                related_name="test_collection_visibility",
                to="auth.group",
                verbose_name="Visible to",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfo",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Uncheck to disable this test on this unit",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfo",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="QC group that this test list should nominally be performed by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfo",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.test",
                verbose_name="Test",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfo",
            name="tolerance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.tolerance",
                verbose_name="Tolerance",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfo",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="units.unit",
                verbose_name="Unit",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="changed",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Changed"),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="changed_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Changed by",
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="comment",
            field=models.TextField(
                help_text="Reason for the change", verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="reference_changed",
            field=models.BooleanField(verbose_name="Reference Changed"),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="tolerance_changed",
            field=models.BooleanField(verbose_name="Tolerance Changed"),
        ),
        migrations.AlterField(
            model_name="unittestinfochange",
            name="unit_test_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="qa.unittestinfo",
                verbose_name="Unit Test Info",
            ),
        ),
        migrations.RunPython(
            restore_unique_constraints,
            remove_restored_unique_constraints,
        ),
    ]
