"""Drop the configurable date format hint from work_completed's help_text.

A field's help_text is part of its migration state, so building it from
settings.DATETIME_HELP meant any site changing its date format had a pending
migration of its own. The QA form already sets this help text itself, so the
model was carrying a copy that nothing rendered.

No database change: help_text is metadata.
"""

# Generated by Django 4.2 on 2026-09-19 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0060_v4_0_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='work_completed',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Work Completed'),
        ),
    ]
