# Generated by Django 2.2.18 on 2021-12-24 04:55

from django.db import migrations, models
import django.db.models.deletion
import qatrack.qa.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0061_tistatus_to_tlistatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlist',
            name='autoreviewruleset',
            field=models.ForeignKey(blank=True, default=qatrack.qa.models.default_autoreviewruleset, help_text='Choose the Auto Review Rule Set to use for this Test List. Leave blank to disable.', null=True, on_delete=django.db.models.deletion.PROTECT, to='qa.AutoReviewRuleSet', verbose_name='Auto Review Rules'),
        ),
        migrations.AlterField(
            model_name='autoreviewruleset',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Check this option if you want this to be the default rule set for test lists', verbose_name='Default'),
        ),
    ]
