# Generated by Django 2.2.18 on 2021-12-24 04:56
import logging

from django.db import migrations
from qatrack.qa.models import TestList


logger = logging.getLogger("qatrack.migrations")


def test_arrs_to_test_list_arrs(apps, schema):

    for test_list in TestList.objects.all():
        tests = test_list.all_tests()
        arrs = tests.exclude(autoreviewruleset_id=None).values_list("autoreviewruleset_id", flat=True)
        no_auto_review = len(arrs) == 0
        if no_auto_review:
            continue

        all_have_auto_review = len(arrs) == len(tests)
        rules_all_same = len(set(arrs)) == 1
        uniform_rules =  rules_all_same and all_have_auto_review
        if uniform_rules:
            test_list.autoreviewruleset = arrs[0]
            test_list.save()
        else:
            msg = (
                f"Tests from Test List '{test_list.name}' did not have uniform auto review rules. "
                "Please set the auto review rule set for this test list manually"
            )
            print(msg)
            logger.warning(msg)


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0062_testlist_autoreviewruleset'),
    ]

    operations = [
        migrations.RunPython(test_arrs_to_test_list_arrs, lambda apps, schema: None),
    ]
