# Generated by Django 2.2.18 on 2021-12-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0063_set_test_list_auto_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='autoreviewruleset',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='status',
        ),
    ]
