# Generated by Django 2.2.18 on 2022-01-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0064_auto_20211224_1243'),
        ('qa', '0059_add_default_ref_tols'),
    ]

    operations = [
    ]
