# Generated by Django 2.2.18 on 2022-07-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0065_merge_20220123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittestinfo',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
        migrations.AlterField(
            model_name='unittestinfochange',
            name='unit_test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.UnitTestInfo'),
        ),
    ]
