# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
