# Generated by Django 4.2 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
    ]
